---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc
  namespace: networking
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 8Gi

  storageClassName: rook-ceph-block