---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  releaseName: unifi
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.9.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v7.1.61
    persistence:
      data:
        enabled: true
        existingClaim: unifi-pvc
    env:
      TZ: "America/Phoenix"
    runAsRoot: false
    ingress:
      main: 
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "unifi.${SECRET_DOMAIN}"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${UNIFI_LB}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: unifi
        ports:
          http:
            port: 8443
            protocol: HTTPS
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          portal-http:
            enabled: false
            port: 8880
            protocol: HTTP
          portal-https:
            enabled: false
            port: 8843
            protocol: HTTPS
          speedtest:
            enabled: false
            port: 6789
            protocol: TCP
          stun: 
            enabled: false
            port: 3478
            protocol: UDP
          syslog:
            enabled: false
            port: 5514
            protocol: UDP
          discovery:
            enabled: false
            port: 10001
            protocol: UDP
      udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${UNIFI_LB}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: unifi
        ports:
          stun: 
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: false
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
