---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  releaseName: lidarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lidarr
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v1.0.0.2515
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
        - host: "grooves.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "grooves.${SECRET_DOMAIN}"
    podSecurityContext:
      runAsGroup: 100
      runAsUser: 1000
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
      media:
        enabled: true
        existingClaim: nfs-media-music-pvc
      downloads:
        enabled: true
        type: custom
        mountPath: "/downloads"
        readOnly: false
        volumeSpec:
          nfs:
            server: 192.168.1.50
            path: "/mnt/user/downloads"
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
