apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-books-pv
spec:
  storageClassName: media-books
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.7.7
    path: "/mnt/user/media/books"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-books-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-books
  resources:
    requests:
      storage: 1Mi