# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: security
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:752qD0UktOKBST8t76BPAT+xWV0UkKGygXJ1Vpajneo0wWQ5X4hUeuFPu5RhvtDZN4jQ5An0lIMlQ0wZEkPMeA==,iv:TWvKopveWHCeU/BSrBAeTGD9QvvUG24xfLyAC1GqJnM=,tag:pqGfOyK2FNDP/H3fzv0tlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzj03r3dv3xrvtns0v0ufs4pvchw3u0564u36hc5h3vmxqu3gkq3wmu9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc0I5ZjZKclJpWFp0bmRl
            TlpGaGcvVEorU2FrdUpxZ0EyVFZzUEl3ZEFJCmJ5RU9pRk5qeDRSSlJjUEVxY2w0
            cTNaY1pYT3JMTjNhUUdLZUlXT3ZDckEKLS0tIEpBa0ZaRWhRMGplNGFUSFRIbVk3
            WE1RdUc5Szh2ajRwVHp4NDdiZGVtdHMKtUDepNaZtxhDd+FokYG4XCw1n0nbAbRx
            vTtJQltwKgdckMqlYo1YBJ/FbfI/zuI6WycupVp/K7Mo5vB81pIInw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T01:53:09Z"
    mac: ENC[AES256_GCM,data:qy2PbB7sdlY8u9ydpDxFEzz+wep8SS/KK7LIkXUE7LQBVSDQVZusg6gGKx78EZZXe0xtzIb8KWfnduPbiT1ihioW5Uuyv6TzexsU5xYk/8u7oaA4zhhnfizpraIBAoTH++GuaXwpYHd8/5U+rEbR9KBgJD87dXJQpU2qu5CYS0c=,iv:H2Iy7VHkDYeKpV9C53jQQ9nJxxEAcoglAIOcdLXfWeo=,tag:Wtwu7RTls7emypIj59MDIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
