---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stackgres
  namespace: flux-system
spec:
  interval: 10m
  url: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
  timeout: 3m
