apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 10m
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  timeout: 3m
