---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
