---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: metallb
      namespace: kube-system
  values:
    rbac:
      create: true
    replicaCount: 1
    isClusterService: false
    serviceType: LoadBalancer
    service:
      #loadBalancerIP: 192.168.1.87
      externalIPs:
      - 192.168.69.180
      externalTrafficPolicy: Local
    prometheus:
      service:
        enabled: false
      monitor:
        enabled: false
  valuesFrom:
    - kind: Secret
      name: coredns-values
      optional: false