---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: etcd
      version: 5.6.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    statefulset:
      replicaCount: 1
    auth:
      rbac:
        enabled: false
    persistence:
      enabled: false
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64