---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: networking
spec:
  interval: 5m
  chart: 
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 3.23.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: metallb
      namespace: kube-system
  values:
    controller:
      ingressClass: internal
      replicaCount: 1
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.69.101
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      admissionWebhooks:
        enabled: false
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        custom-http-errors: "404,403,500,503"
        # Setting use-proxy-protocol to true will break the proxy
        use-proxy-protocol: "false"
        proxy-body-size: "50m"
        use-forwarded-headers: "true"
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
          namespace: networking
        prometheusRule:
          enabled: false
          namespace: networking
          rules:
            - alert: TooMany500s
              expr: sum(rate(nginx_ingress_controller_requests{status!~"5.*"}[2m])) / sum(rate(nginx_ingress_controller_requests[2m])) < 0.85
              for: 1m
              labels:
                severity: critical
              annotations:
                description: Too many 5XXs
                summary: More than 15% of the all requests did return 5XX, this requires your attention
            - alert: TooMany400s
              expr: sum(rate(nginx_ingress_controller_requests{status!~"4.*"}[2m])) / sum(rate(nginx_ingress_controller_requests[2m])) < 0.85
              for: 1m
              labels:
                severity: critical
              annotations:
                description: Too many 4XXs
                summary: More than 15% of the all requests did return 4XX, this requires your attention
      extraArgs:
        default-ssl-certificate: "networking/acme-crt-secret"
      resources:
        requests:
          memory: 150Mi
          cpu: 50m
        limits:
          memory: 300Mi
    defaultBackend:
      enabled: false
      image:
        repository: onedr0p/custom-error-pages
        tag: v1.0.2
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi