---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  releaseName: unifi
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    image:
      tag: stable-6
    persistence:
      enabled: true
      size: 2Gi
      storageClass: longhorn
    timezone: "America/Phoenix"
    runAsRoot: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    guiService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.82
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.82
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.82
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.82
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
  valuesFrom:
    - kind: Secret
      name: unifi-values
      optional: false