---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./calibre-web/ks.yaml
  - ./jellyseer/ks.yaml
  - ./lidarr/ks.yaml
  - ./podgrab/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  # - ./whisparr/ks.yaml