---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io/
      chart: k10
      version: 4.0.9
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    eula:
      accept: true
      company: Lokiraze
      email: "${SECRET_DO_EMAIL}"
    global:
      persistence:
        storageClass: rook-ceph-block
    auth:
      tokenAuth:
        enabled: true
    clusterName: k8s
    ingress:
      create: true
      host: "k10.${SECRET_DOMAIN}"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      urlPath: k10
      hosts:
        - "k10.${SECRET_DOMAIN}"
      tls:
        enabled: true
        secretName: tls.k10