---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: dev
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://charts.drone.io
      chart: drone
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: flux-system
  values:
    image:
      repository: drone/drone
      tag: 2.13.0
    persistentVolume:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - host: &host drone.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    env:
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_GITEA_CLIENT_ID: ${SECRET_DRONE_GITEA_CLIENT_ID}
      DRONE_GITEA_CLIENT_SECRET: ${SECRET_DRONE_GITEA_CLIENT_SECRET}
      DRONE_GITEA_SERVER: ${SECRET_DRONE_GITEA_SERVER}
      DRONE_RPC_SECRET: ${SECRET_DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: *host
      DRONE_SERVER_PROTO: https
      DRONE_USER_CREATE: username:bobert,machine:true,token:0f1cf412bf6d520ef111438f5330d2eb
