apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  annotations:
    kubernetes.io/ingress.class: external
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
spec:
  rules:
  - host: "media.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port: 
              number: 8096
  tls:
  - hosts:
    - "media.${SECRET_DOMAIN}"
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: default
spec:
  ports:
  - name: http
    port: 8096
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin
  namespace: default
subsets:
  - addresses:
    - ip: 192.168.1.50
    ports:
    - port: 8096
      name: http