apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stash
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-body-size: 0
spec:
  ingressClassName: internal
  rules:
  - host: "stash.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stash
            port: 
              number: 9999
  tls:
  - hosts:
    - "stash.${SECRET_DOMAIN}"
---
apiVersion: v1
kind: Service
metadata:
  name: stash
  namespace: default
spec:
  ports:
  - name: http
    port: 9999
---
apiVersion: v1
kind: Endpoints
metadata:
  name: stash
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.50
    ports:
      - port: 9999
        name: http