---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app whisparr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/whisparr-nightly
      tag: 0.1.0.49@sha256:c0587dea2c67627f14ad12c03c2c237b12c96be27c1d2632829f41465ca3ff79
    env:
      TZ: "${TIMEZONE}"
      WHISPARR__INSTANCE_NAME: Whisparr
      WHISPARR__PORT: &port 8989
      WHISPARR__BRANCH: nightly
      WHISPARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
      WHISPARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: whisparr-config
      nfs-nas-media:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: "/mnt/user/media/other"
        mountPath: /media
        readOnly: false
