---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres
spec:
  interval: 5m
  chart:
    spec:
      chart: stackgres-operator
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: stackgres
        namespace: flux-system
      interval: 5m
  values:
    operator:
      image:
        tag: "1.2.1"
    restapi:
      image:
        tag: "1.2.1"
    jobs:
      image:
        tag: "1.2.1"
    adminui:
      image:
        tag: "1.2.1"
    prometheus:
      allowAutobind: false
