---
apiVersion: v1
kind: Endpoints
metadata:
  name: &app frigate
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
subsets:
  - addresses:
      - ip: ${NFS_SERVER}
    ports:
      - port: 5000
        name: http
