---
apiVersion: v1
kind: Service
metadata:
  name: &app frigate
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ports:
    - name: http
      port: &port 5000
      protocol: TCP
      targetPort: *port
