apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: security
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:Yiw9o14gzgpeQt6CxQeBGDg/h+ng1A5kdf561pjsYKQ8V2tGdiRyDaxw6oXkuxFPJrBJ6YYxCoXshY4nBDE=,iv:mylVvyxMqJmLVckg4o6EnWgy1alNOjWJHTA1xgwUOTo=,tag:LJkcs295e4ocMdrC5DgBqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzj03r3dv3xrvtns0v0ufs4pvchw3u0564u36hc5h3vmxqu3gkq3wmu9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bXl3YVJJY21mbGNqcEo1
            cnA2OVM5UCtwaFdYeHh3WE9zcDArTUVURzJ3CnIvYlJMYkFNb1k1elBoaHJhZVlL
            bjJTSnFDZnpLSGtRNXprU3ZvQWdHTkUKLS0tIGVqRGRUQ29adUZiYTFkU2JpOHFS
            MFROTmJ6WXpxRFN1UXIwOEdVak14SVEKjb0n3KknjwAXFBU8GT/voOJrtMdIXrnh
            JMb3u20NAzmvBAr+p+eBDngb+YS9RH4pqJUS+hfS9aGT8akG/3jJ3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T16:45:37Z"
    mac: ENC[AES256_GCM,data:vYRLrtcihHIW4Rbk53hAc3nfTsy8ojpfXAQ12Bi0NRtDubpFfwP4zcTR1Klzsyt3OXMShteD4X/y//qSLd+xw1pdMtZMhSYmIP2sfZ0gUp3vS3YOGHrqW3T5SiNdui/MBWdrueKu22AhDD/h6KWlJpqQ2gQtSydGXmAy/gu7KxM=,iv:WFEu8S5zapaNsdYzlIoFdn07RYDh0efbQ4v/bvP3f50=,tag:/5itVPRVSLRuGLxg2Y2xnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
