apiVersion: v1
kind: Secret
metadata:
    name: recyclarr
    namespace: media
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:QFbIP6wiVegJOEztIO1qwFFRN+T4coObU0g81fBUvr0=,iv:pewRXdz9LC25DE5VdSY4moubKLgzINX5M7jYaMaja4o=,tag:So9UEwxuAE+3FOka8EcDnA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:jSqHzi+/npsjIQapji68DAX4jejeyI08Z+3Pr6ciVLg=,iv:4pJDIC187TF0hhe0y+OXHfiZYKGNaX3f4VCxJFGjqDs=,tag:CwinU6IU5Plmt7HnUHFcNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzj03r3dv3xrvtns0v0ufs4pvchw3u0564u36hc5h3vmxqu3gkq3wmu9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZVFwN2txbEhFT0QrazRB
            MFQxUG1mZkpUejlYUUdJRVNYYmhVZjNuckE0CkhQU0x6akF1R3lSYUVQTk5nNzlK
            WlVrNUhqaURnQU1Xem9nQ2ltdDJNbkUKLS0tIFJSNWdWdXhlTldNQWdoMFRZQVZo
            UFNQK3NUb3NpVFBnY2tVZkV1aDZIbncK6OjyqApD7oA0Gl2ozb1Iv+I6M/lTMW7T
            AQd39QY9uE0fax2KJxHU+l9VTUxQj3RiKcaCVdvy/Gto2JTFblC3Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-13T02:12:40Z"
    mac: ENC[AES256_GCM,data:nQU/WJrhKMAZGKgTQmYTjc0rTjS0X82GN2Nv5pzQ6GHI88yTuR/8R6rtAuG1IjU4xJ2lfATwl1bRTuNVvdpCz9d8pIj5jXbqDJQUr5rob8Ze9bJDxEMLu4/iH42QN69dU+GDCy6UpKiBoRF7dspOiQQfLnx7vAqlukTPtEB8fHA=,iv:zP/dq+zV6xzqVBPOmYdG6q2XGzp+VGDYqCrfUMiwm00=,tag:FiTv7N7uN5dcjrfaTLyroQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
