---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: security
spec:
  interval: 5m
  releaseName: *app
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.25.2
    envFrom:
      - secretRef:
          name: *app
    env:
      TZ: "${TIMEZONE}"
      DOMAIN: https://passwords.${SECRET_DOMAIN}
      SIGNUPS_ALLOWED: "true"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host passwords.${SECRET_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    resources: {}
