---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.22.2
    env:
      TZ: "America/Phoenix"
      DOMAIN: https://passwords.${SECRET_DOMAIN}
      SIGNUPS_ALLOWED: "true"
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "external"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
        - host: passwords.${SECRET_DOMAIN}
          paths:
          - path: /
        tls:
        - hosts:
          - passwords.${SECRET_DOMAIN}
    resources: {}