# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: digitalocean-api-key
    namespace: kube-system
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:v6oo5XdQjI7kynA1kgMK97/DKbm/jLKgdyZDKIiy9xBrhCHabiaTe1kogc9rFX7QUREHP/gIbuMUwPxm1bBFtQ==,iv:Oc4fQj+SJU7PRbXQL2bBNAEmg21kHMVjDWv77gSpRsc=,tag:BjUD3ZHX5G4Q+ZU0hnTA5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzj03r3dv3xrvtns0v0ufs4pvchw3u0564u36hc5h3vmxqu3gkq3wmu9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y0Z3ak5JUjl1Um5qNkh5
            K0NIRGtTYWVsZ0ZWb1pQZ0xwU2xaUk95Nmp3Ckg0Wm1xM2VhaEkyNnF3YVN2Nm1L
            YW92NlR3RGl6RGVXUWRrNjlFTmppK1EKLS0tIE9Kb1gxeCt2cUlxc2tZWXdGcWJM
            VU5QUTlveWRoL0FaZjRQbHN4WXl0bk0K5FuISbirN4vRYPst84WgdPGDqODDcbzv
            9KM43B+hYvMKydtnhmKgPST+pMDqU4uNrku1R2Ca79P0sS7AeCDihw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T01:25:31Z"
    mac: ENC[AES256_GCM,data:9Zg8mVV+WT2W/Ql385qzOWrouTbtpqKOWI9bOlS4JcI8MPS2IxcbwbtYIqdGJyWUgUQGhslozgaWT8FxMLZAz1eMaw8AA/HDkyWXlSKbsIJgLwVBszhphS9ISRutW1NWxNRL45AMitQM4a5gzvDx0jjmEyi9h00I+Lc7Hry77HE=,iv:8ADD2IeNP+tD/KayO2EPUeZyUK680KT9Odd22fGKa9Y=,tag:9U3X54YEDfVVoxR3ASjNCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
