---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: home
  annotations:
    # fluxcd.io/automated: "false"
    # fluxcd.io/tag.chart-image: 'regexp:^(v[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: bitwarden
  rollback:
    enable: true
  chart:
    repository: https://cdwv.github.io/bitwarden-k8s/
    name: bitwarden-k8s
    version: 0.1.5
  values:
    nameOverride: bitwarden
    fullnameOverride: bitwarden
    image:
      repository: bitwardenrs/server
      tag: latest
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
  valueFileSecrets:
    - name: "bitwarden-helm-values"