---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  releaseName: frigate
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: blakeshome-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: blakeblackshear/frigate
      tag: stable-armv7
    coral:
      enabled: true
    shmSize: 3Gi
    timezone: "America/Phoenix"
    persistence:
      data:
        enabled: true
        storageClass: longhorn   
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tpu
              operator: In
              values:
              - google-coral
  valuesFrom:
    - kind: Secret
      name: frigate-values
      optional: false
