---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grocy
  namespace: home
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'semver:0'
spec:
  releaseName: grocy
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: grocy
    version: 2.0.0
  values:
    image:
      repository: linuxserver/grocy
      tag: v3.0.1-ls86
    persistence:
      enabled: true
      storageClass: "nfs-client"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Phoenix"
    enableProjects: true
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valueFileSecrets:
  - name: "grocy-values"