---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grocy
  namespace: home
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'semver:0'
spec:
  releaseName: grocy
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: grocy
    version: 2.0.0
  values:
    image:
      repository: linuxserver/grocy
      tag: v2.6.1-ls51
    persistence:
      enabled: true
    ingress:
      enabled: true
    timezone: "America/Phoenix"
    enableProjects: true
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valueFileSecrets:
  - name: "grocy-values"