---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: home
spec:
  releaseName: grocy
  interval: 5m
  chart:
    spec:
      chart: grocy
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/grocy
      tag: v3.0.1-ls89
    persistence:
      config:
        enabled: true
        storageClass: longhorn
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Phoenix"
    enableProjects: true
    resources:
      requests:
        memory: 150Mi
        cpu: 10m
      limits:
        memory: 350Mi
  valuesFrom:
    - kind: Secret
      name: grocy-values
      optional: false