---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: home
spec:
  releaseName: heimdall
  interval: 5m
  chart:
    spec:
      chart: heimdall
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/heimdall
      tag: version-2.2.2
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valuesFrom:
    - kind: Secret
      name: heimdall-values
      optional: false