---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: home
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    #fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: heimdall
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: heimdall
    version: 4.1.2
  values:
    image:
      repository: linuxserver/heimdall
      tag: version-2.2.2
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valueFileSecrets:
  - name: "heimdall-values"