---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
  annotations:
    fluxcd.io/ignore: "false"
    #fluxcd.io/automated: "true"
    #fluxcd.io/tag.chart-image: semver:~0.
    #filter.fluxcd.io/chart-image: semver:~0.
    #filter.fluxcd.io/vscode: "regex:^3.[0-9]+-.*$"
spec:
  releaseName: home-assistant
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 5.4.4
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.2.0
    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClass: "nfs-client"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.org/websocket-services: home-assistant
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.84
    hostNetwork: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    postgresql:
      enabled: false
    zwave:
      enabled: false
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 35m
        memory: 2000Mi
  valueFileSecrets:
  - name: "home-assistant-values"