---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  releaseName: home-assistant
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: metallb
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.3.4
    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClass: longhorn
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
        nginx.org/websocket-services: home-assistant
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.69.140
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    postgresql:
      enabled: false
    zwave:
      enabled: false
    addons:
      codeserver:
        enabled: true
        image:
          tag: 3.9.0
        args:
          - --auth
          - none
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        workingDir: "/config"
        volumeMounts:
          - name: config
            mountPath: /config
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "internal"
    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 350m
        memory: 250Mi
  valuesFrom:
    - kind: Secret
      name: home-assistant-values
      optional: false