---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: icantbelieveitsnotvaletudo
  namespace: home
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'semver:0'
spec:
  releaseName: icantbelieveitsnotvaletudo
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: icantbelieveitsnotvaletudo
    version: 1.0.0
  values:
    image:
      repository: rand256/valetudo-mapper
      tag: latest
    replicaCount: 1
    config:
      mapsettings:
        drawPath: true
        drawCharger: true
        drawRobot: true
        scale: 4
      mqtt:
        identifier: "rockrobo"
        topicPrefix: "valetudo"
        autoconfPrefix: "homeassistant"
        broker_url: "mqtt://mosquitto:1883"
        mapDataTopic: "valetudo/rockrobo/map_data"
        minMillisecondsBetweenMapUpdates: 10000
        publishMapImage: true
      webserver:
        enabled: true
        port: 3000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"