---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  releaseName: eclipse-mosquitto
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: mosquitto
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: metallb
      namespace: kube-system
  values:
    image:
      repository: eclipse-mosquitto
      tag: 1.6.12
    replicaCount: 1
    serviceMonitor:
      create: true
    persistentVolume:
      enabled: false
    service:
      type: LoadBalancer
      externalIPs:
      - 192.168.69.110
      #loadBalancerIP: 192.168.1.81
      mqtt:
        enabled: true
        port: 1883                                                              # Default port. Here for visability
      mqtts:
        enabled: false                                                          # Disabled, too much work to get cert inside pod
        port: 8883                                                              # Default port. Here for visability
      ws:
        enabled: true
        port: 8080                                                              # Default port. Here for visability
    statefulset:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"