---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  releaseName: eclipse-mosquitto
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: metallb
      namespace: kube-system
  values:
    image:
      repository: eclipse-mosquitto
      tag: 1.6.14
    persistence:
      enabled: false
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.69.4
      port:
        port: 1883
        name: mqtt
