---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  releaseName: node-red
  interval: 5m
  chart:
    spec:
      chart: node-red
      version: 7.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 1.3.5
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    timezone: "America/Phoenix"
    enableProjects: true
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: node-red-values
      optional: false