---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+-12-minimal)$'
spec:
  releaseName: node-red
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: node-red
    version: 3.1.0
  values:
    image:
      repository: nodered/node-red
      tag: 1.1.3-12-minimal
    persistence:
      enabled: true
    flows: "flows.json"
    ingress:
      enabled: true
    timezone: "America/Phoenix"
    enableProjects: true
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valueFileSecrets:
  - name: "node-red-values"