---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octoprint-ender3
  namespace: home
spec:
  releaseName: octoprint-ender3
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: octoprint
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      tag: 1.5.3
    env:
      TZ: America/Phoenix
      ENABLE_MJPG_STREAMER: "true"
      MJPG_STREAMER_INPUT: "-y -n -r 640x480"
      CAMERA_DEV: /dev/video
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    persistence: 
      data:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
    additionalVolumeMounts:
      - name: printer
        mountPath: /dev/ttyACM0
      - name: camera
        mountPath: /dev/video0
    additionalVolumes:
      - name: printer
        hostPath:
          path: /dev/ttyACM0
      - name: camera
        hostPath:
          path: /dev/v4l/by-id/usb-046d_HD_Pro_Webcam_C920_704715BF-video-index0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: usb
              operator: In
              values:
              - ender3
  valuesFrom:
    - kind: Secret
      name: octoprint-values
      optional: false
