---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: octoprint-ender3
  namespace: home
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: octoprint-ender3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: octoprint
    version: 2.2.2
  values:
    image:
      tag: 1.5.2
    env:
      TZ: America/Phoenix
      ENABLE_MJPG_STREAMER: "true"
      MJPG_STREAMER_INPUT: "-y -n -r 640x480"
      CAMERA_DEV: /dev/video
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    persistence: 
      data:
        enabled: true
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: 1Gi
    additionalVolumeMounts:
      - name: printer
        mountPath: /dev/ttyACM0
      - name: camera
        mountPath: /dev/video0
    additionalVolumes:
      - name: printer
        hostPath:
          path: /dev/serial/by-id/usb-LeafLabs_Maple-if00
      - name: camera
        hostPath:
          path: /dev/v4l/by-id/usb-046d_HD_Pro_Webcam_C920_704715BF-video-index0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: usb
              operator: In
              values:
              - ender3
  valueFileSecrets:
  - name: "octoprint-values"