---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: home
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^(6\.[0-9][0-9]\.[0-9]+)$'
spec:
  releaseName: unifi
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: unifi
    version: 0.10.0
  values:
    image:
      repository: ryansch/unifi-rpi
      tag: 6.1.16
    persistence:
      enabled: true
      size: 2Gi
    timezone: "America/Phoenix"
    runAsRoot: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    guiService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.82
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.82
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.82
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.82
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
  valueFileSecrets:
  - name: "unifi-values"