---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zwave2mqtt
  namespace: home
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: zwave2mqtt
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: zwave2mqtt
    version: 5.4.0
  values:
    image:
      repository: zwavejs/zwavejs2mqtt
      tag: 1.0.4
    env:
      TZ: America/Phoenix
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    persistence: 
      config:
        enabled: true
        storageClass: "nfs-client"
    additionalVolumeMounts:
      - name: usb
        mountPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_6120113C-if00-port0
    additionalVolumes:
      - name: usb
        hostPath:
          path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_6120113C-if00-port0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: usb
              operator: In
              values:
              - zwave
  valueFileSecrets:
  - name: "zwave2mqtt-values"