apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 10m0s
  releaseName: metallb
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.3.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    configInline:
      peers:
        - peer-address: 192.168.1.1
          peer-asn: 64512
          my-asn: 64513
      address-pools:
        - name: default
          protocol: bgp
          avoid-buggy-ips: true
          addresses:
            - 192.168.69.0/24
      # address-pools:
      # - name: default
      #   protocol: layer2
      #   addresses:
      #   - 192.168.1.80-192.168.1.100
    prometheus:
      serviceMonitor:
        enabled: false
      prometheusRule:
        enabled: false
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.6
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.6
