---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 128Mix
