---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jellyseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: overseerr
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
    image:
      repository: fallenbagel/jellyseerr
      tag: develop
    env:
      TZ: "${TIMEZONE}"
      LOG_LEVEL: "info"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: eye-circle
        hosts:
          - host: &host "requests.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: jellyseerr-config
        mountPath: /app/config
