---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 6.2.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: external-dns
    image:
        repository: raspbernetes/external-dns
        tag: 1a8e2310ca97a3758d85a3a435e491911a486e7d
    interval: "5m"
    logLevel: debug
    sources:
    - service
    - ingress
    provider: coredns
    coredns:
      etcdEndpoints: http://etcd:2379
    policy: sync
    domainFilters:
    - "${SECRET_DOMAIN}"
    crd:
      create: false
      apiversion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
