---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  releaseName: audiobookshelf
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: audiobookshelf
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: advplyr/audiobookshelf
      tag: 2.0.8
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "audiobooks.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "audiobooks.${SECRET_DOMAIN}"
    env:
      TZ: "America/Phoenix"
      AUDIOBOOKSHELF_UID: 568
      AUDIOBOOKSHELF_GID: 568
    persistence:
      config:
        enabled: true
        existingClaim: audiobookshelf-config
      metadata:
        enabled: true
        existingClaim: audiobookshelf-metadata
      media:
        enabled: true
        existingClaim: nfs-media-books-pvc
        subPath: audiobooks
