apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 64513
   exportPodCIDR: true
   serviceSelector:
    matchExpressions:
      - { key: thisFakeSelector, operator: NotIn, values: [ 'will-match-and-announce-all-services' ] }
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: "192.168.1.1/32"
      peerASN: 64512