apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 64513
   exportPodCIDR: true
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: "192.168.1.1"
      peerASN: 64512