---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
spec:
  releaseName: ombi
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ombi
      version: 11.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/ombi
      tag: version-v4.0.1342
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-body-size: 100m
          nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
        hosts:
          - host: "choose.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "choose.${SECRET_DOMAIN}"
    env:
      TZ: "America/Phoenix"
    persistence:
      config:
        enabled: true
        existingClaim: ombi-config
