# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hRhr0KAS5+AcGPWk,iv:Ch5GJ9CMCfUH4DicE6c1aGfuMfrW7+lEI0aRgiwWrsU=,tag:SfxzU+j8AS9GtII0gnLIZA==,type:str]
    SECRET_DIGITALOCEAN_EMAIL: ENC[AES256_GCM,data:3DtLuv57o/cuf2wgeMlZaUmyLloPDTMhrXE=,iv:6qkf8fbdsg3rLAoDOt8xOljqBTbcYLqgKe41xoujylU=,tag:q8HDjgxAZADOIHdWtyGKgg==,type:str]
    SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:5zzBqsBOnDL2NjtlaT39Z7Zl,iv:kyVUdbgUM5U5vxzSwg26GWBr/yfhv2g6v5/GuoIbjEQ=,tag:k2DnJlHoyrPQ/RR8ZC2iIg==,type:str]
    SECRET_LDAP_ADMIN_USERNAME: ENC[AES256_GCM,data:oEiJ/EsE+ZI=,iv:6Y9G22fsWYEnuiwi9t2eFz6EkMLGpBZsmdL7Xb9XujY=,tag:dMllT1lyCJXN0KwXmP0oIg==,type:str]
    SECRET_LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:G2fivd69anm9JmjFA+3R7Q==,iv:GpqxeqU5cY5lrs1G/zOfT65tNs5Aa9WQ4WLP+VwZj1E=,tag:6p92146njtk4Kz6vqnAulg==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:u/6vtQucINKWK3ZWLo75Lw==,iv:2nRY6i7c1X+Qj1KQmGigB1P0vzSpWCqm6WCqLUHuw5c=,tag:w4kQBOPZZ3DPABd78BdIFg==,type:str]
    SECRET_SMTP_USER: ENC[AES256_GCM,data:Dwc7Km0OBDZlJoHtLu1xAI0IzvRguyC7BZ8=,iv:83PSjT05UeGoqpWecdjoGSS/17Pxu9uGSLbqku3Dzes=,tag:RY2EOc/8SdJgZ82qIoRFLw==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:Yj8/dDOqAzjvvkTwRUy3eIH4w+vytxOy7/scnMLTMq16HnjZb8SKrgs7AsSX+2M0LHU=,iv:7b/ST+DepjMLF88JWOqp8pnCMYoWs2kFVlx//gA7CMI=,tag:wTwxLwqk0eAGJgrmXBCqYQ==,type:str]
    SECRET_AUTH_POSTGRES_PASSWORD: ENC[AES256_GCM,data:8e+mRneShIXdqFv6zUJraDkoZKlD99AbBeg=,iv:5O+ynQAdv5L0wBc8sseKHNXiLoPsnJN1GrE6LB1rTOs=,tag:BxGlMQv9D/YNKr+wsv5AMQ==,type:str]
    SECRET_AUTH_REDIS_PASSWORD: ENC[AES256_GCM,data:lI51IG9pybSBMMKoo0PXQs/Gxws7VsDdxkA7,iv:ZpBW6vL/hAltmjH6hIhHkxtuAjmbwry+ke0xx0kCyis=,tag:KbXNcGs/67AYm/LGy8VC4w==,type:str]
    SECRET_MATRIX_REDIS_PASSWORD: ENC[AES256_GCM,data:90PuNF3rY3H4S5Ns3YFMO5z9w0g2h68R9fK8JuqBqD4uzee9lcaQnPr21f3sLiRNiu4X4eb8OdE2yakoYMWRBg==,iv:laL2U9LFkQvBGSncPkiMchxuijTgkLdTsP6uJ84CKxI=,tag:ItgU50Huh0YmOVfgwSEuCA==,type:str]
    SECRET_MATRIX_POSTGRES_PASSWORD: ENC[AES256_GCM,data:n3AFWKF1ZR1YIO9+JhS14s2ehvCupWkBgxppY8DJqzmuccubSmrFvbVVZvdH7JFngzo1TQhOn41nLAYI8yT+gQ==,iv:4ZphHFeobkhweM0W3TvzNo9i0IBek/A7sd1bT044x9g=,tag:ZNujOnswSN9ccnlEWRTrZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzj03r3dv3xrvtns0v0ufs4pvchw3u0564u36hc5h3vmxqu3gkq3wmu9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN2p0alhlSlJ6VDVPMVJs
            cTNJN2RiNzJ4cVRISFdZK3hlNkxVdnVjdlNzCjlJNGZTUUpObmNIYndRSEVlbmsv
            eUVXc2FZWG84UDZqdlVpY2ZqUDFuOUEKLS0tIC80RDR0Q0dqSHdWWHU5ZCtOWUdP
            cHd5QjFkMkM3NUUyZ2tSZE1vRGliSWMK2/o77jbO46DwRw0DgEdfFnfDyGWqMw4k
            Yohw8jSypOqugCyxe7Ofup/ZM6Ihb0bBNvMrfWcTZ7dTrllxVTnkYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T16:25:01Z"
    mac: ENC[AES256_GCM,data:c7V19J2SgnOPdpgDztOEHsy4MdFW8Ix7EvrkPwN/dkZwAEEy1SXGJFfcr6i9yXt1dZ5cncEJ2b8HdLkX2dg0x/g/UJAnhmKIHWBGEy2PcLAdOYB1M2n0RIDIwRQPJ/UB7JpfsyTT1PYblIz0emw2T0YwDShBlguR6gaA5awGVXQ=,iv:XfsjLH9eYhRB1VRQ/Zg325kJ/MIH2Xde7Df4OMJDDGo=,tag:KT/T0gorn5QrBBLOPqtH8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
