---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-books-pv
spec:
  storageClassName: nfs-media-books
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.50
    path: "/mnt/user/media/books"
  mountOptions:
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime