---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-kubernetes-secrets
  namespace: dev
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://charts.drone.io
      chart: drone-kubernetes-secrets
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: flux-system
  values:
    rbac:
      secretNamespace: dev
    env:
      KUBERNETES_NAMESPACE: dev
      SECRET_KEY: ${SECRET_DRONE_PLUGIN_TOKEN}
