---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: komga
  namespace: media
spec:
  releaseName: komga
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: komga
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gotson/komga
      tag: 0.142.0
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "manga.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "manga.${SECRET_DOMAIN}"
    env:
      TZ: "America/Phoenix"
    persistence:
      config:
        enabled: true
        existingClaim: komga-config
      data:
        enabled: true
        existingClaim: nfs-media-books-pvc
        subPath: manga
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
