---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: longhorn
  helmVersion: v3
  chart:
    repository: https://charts.longhorn.io
    name: longhorn
    version: 1.1.0
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      backupTarget: s3://longhorn@minio/backups
      backupTargetCredentialSecret: minio-admin-token
      defaultReplicaCount: 2
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
  valuesFrom:
    - kind: Secret
      name: longhorn-values
      optional: false