---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: openebs
  helmVersion: v3
  chart:
    repository: https://openebs.github.io/charts
    name: openebs
    version: 1.12.3
  values:
    rbac:
      pspEnabled: true
    ndm:
      sparse:
        count: '1'
    webhook:
      image: 'openebs/admission-server-arm64'
    apiserver:
      image: 'openebs/m-apiserver-arm64'
      sparse:
        enabled: true
    localprovisioner:
      image: 'openebs/provisioner-localpv-arm64'
    snapshotOperator:
      controller:
        image: 'openebs/snapshot-controller-arm64'
      provisioner:
        image: 'openebs/snapshot-provisioner-arm64'
    provisioner:
      image: 'openebs/openebs-k8s-provisioner-arm64'
    cstor:
      pool:
        image: 'openebs/cstor-pool-arm64'
      poolMgmt:
        image: 'openebs/cstor-pool-mgmt-arm64'
      target:
        image: 'openebs/cstor-istgt-arm64'
      volumeMgmt:
        image: 'openebs/cstor-volume-mgmt-arm64'
    policies:
      monitoring:
        image: 'openebs/m-exporter-arm64'