---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  releaseName: helm-operator
  helmVeresion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
    version: 1.2.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/lokiraze/k3s-gitops/main/cluster/flux/helm-operator/helm-operator-values.yaml