image:
  repository: docker.io/raspbernetes/helm-operator
  tag: v1.2.0
createCRD: false
chartsSyncInterval: "5m"
statusUpdateInterval: "60s"
git:
  ssh:
    secretName: flux-git-deploy
helm:
  versions: "v3"
prometheus:
  enabled: false
  serviceMonitor:
    create: false
    namespace: flux
    interval: 30s
    scrapeTimeout: 10s
resources:
  requests:
    cpu: 500m
    memory: 1000Mi
  limits:
    memory: 4000Mi