---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podgrab
  namespace: media
spec:
  releaseName: podgrab
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: podgrab
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/akhilrex/podgrab
      tag: 1.0.0
    ingress:
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts: 
        - host: "podcasts.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
      - hosts:
        - "podcasts.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: podgrab-config
