---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app podgrab
  namespace: media
spec:
  releaseName: *app
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nicholaswilde.github.io/helm-charts/
      chart: podgrab
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde
        namespace: flux-system
      interval: 5m
  values:
    strategy:
      type: Recreate
    image:
      repository: ghcr.io/akhilrex/podgrab
      tag: 1.0.0
    env:
      CHECK_FREQUENCY: "240"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "book-music"
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.security.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Method $request_method;
      hosts:
        - host: &host "podcasts.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    persistence:
      config:
        enabled: true
        existingClaim: podgrab-config
      assets:
        enabled: true
        mountPath: /assets
        type: nfs
        server: ${NFS_SERVER}
        path: "/mnt/user/media/podcasts"
