---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-podcasts-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-podcasts
  resources:
    requests:
      storage: 1Mi
