---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
