---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: dev
spec:
  releaseName: vikunja
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vikunja
      version: 5.5.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    caddy:
      noTls: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: "todo.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "todo.${SECRET_DOMAIN}"
    additionalContainers:
      api:
        env:
          - name: VIKUNJA_SERVICE_TIMEZONE
            value: ${TIMEZONE}
          - name: VIKUNJA_AUTH_OPENID_ENABLED
            value: true
          - name: VIKUNJA_AUTH_OPENID_ENABLED
            value: true
          - name: VIKUNJA_AUTH_OPENID_REDIRECTURL
            value: https://todo.${SECRET_DOMAIN}/auth/openid/
          - name: VIKUNJA_AUTH_OPENID_PROVIDERS_0_NAME
            value: Authelia
          - name: VIKUNJA_AUTH_OPENID_PROVIDERS_0_AUTHURL
            value: https://auth.${SECRET_DOMAIN}
          - name: VIKUNJA_AUTH_OPENID_PROVIDERS_0_CLIENTID
            value: ${SECRET_VIKUNJA_CLIENT_ID}
          - name: VIKUNJA_AUTH_OPENID_PROVIDERS_0_CLIENTSECRET
            value: ${SECRET_VIKUNJA_CLIENT_SECRET}
    env:
      TZ: ${TIMEZONE}
    persistence:
      files:
        enabled: true
        existingClaim: vikunja-files
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
