---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner-kube
  namespace: dev
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://charts.drone.io
      chart: drone-runner-kube
      version: 0.1.10
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: flux-system
  values:
    image:
      repository: drone/drone-runner-kube
      tag: 1.0.0-beta.5
    rbac:
      buildNamespaces:
        - cicd
    env:
      DRONE_NAMESPACE_DEFAULT: cicd
      DRONE_RPC_SECRET: ${SECRET_DRONE_RPC_SECRET}
      DRONE_SECRET_PLUGIN_TOKEN: ${SECRET_DRONE_PLUGIN_TOKEN}
