kind: Secret
ansible_user: ENC[AES256_GCM,data:mZquytvTfk8=,iv:SYbVdv9O2sxW256oZ3oGFuhKprfeOIn26APODGOa0Hg=,tag:hGApXtlnMpQRvRH7blETIw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:b5HAt7xnKg==,iv:8mfKSDyd5ZyQjTMyczVqvuawwbK7BCZx5ZtqS2h7ydU=,tag:dGS3F/hkkg5ovSrY/GsPyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzj03r3dv3xrvtns0v0ufs4pvchw3u0564u36hc5h3vmxqu3gkq3wmu9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOWxrbi9IZlN2NHJhOVl3
            dWFvYW0xU0hmME1ubXcrWlFLVHBrZUZKbkVzCm0wb00yenI4RS9DQTcwYU5YMDJQ
            M01JeXNkK2dwVGdWTGhNTXViSkZNS0UKLS0tIFdNMnd5WTZuKy9hWFE0Sk1UZGJO
            VytOMldBSmZJclF2TjErMkpDVkFJam8KHQlzOsT58pANK5wzKA5n5oq//1EoVc+o
            gzwNV8M3jOCKpXSWmLm/CKbUfA8NGAb7TN14jC3GQgwP+TA1dL0gVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T19:22:51Z"
    mac: ENC[AES256_GCM,data:ItXNjXdmMuKv7MKM28EK5h3wTnFopclY682LufNsz6OUhWGSe672il5gJC18nL19Lyc4rtTFIfBp60OTLaF3JvdQZEeY8ctV6d8yGFVn/MxJJ+LijygLo2uny3nepv0Mojnh+OLmPt2+IwRe1wMHa3ZcmDo/2zYaQxzSD6O6dDg=,iv:3/IAHV/nQp/SrZEcQCAEG7itOKSMz18f/2wrDUdlPCM=,tag:mb5Ph1U2hVvuuEZlYq1rGw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
