---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: home
spec:
  releaseName: grocy
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: grocy
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/grocy
      tag: 3.3.0
    persistence:
      config:
        enabled: true
        existingClaim: grocy-config
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: food.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "food.${SECRET_DOMAIN}"
    env:
      TZ: America/Phoenix
    resources:
      requests:
        memory: 150Mi
        cpu: 10m
      limits:
        memory: 350Mi
