---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: radarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.1.0.6175
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-body-size: 100m
          nginx.ingress.kubernetes.io/client-body-buffer-size: 100m
        hosts:
          - host: &host "movies.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    env:
      TZ: "${TIMEZONE}"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      media:
        enabled: true
        existingClaim: nfs-media-movies-pvc
      downloads:
        enabled: true
        type: pvc
        existingClaim: nfs-media-downloads-pvc
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
