
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: codecentric
  namespace: flux-system
spec:
  interval: 10m
  url: https://codecentric.github.io/helm-charts
  timeout: 3m