---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets-chart
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://bitnami-labs.github.io/sealed-secrets