---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: devops
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(version-v0\.16\.[0-9]+)$'
spec:
  releaseName: bookstack
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: bookstack
    version: 1.2.1
  values:
    image:
      repository: linuxserver/bookstack
      tag: version-v0.30.2
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      TZ: "America/Phoenix"
      PUID: 1000
      PGUID: 1000
    persistence:
      uploads:
        storageClass: "nfs-client"
      storage:
        storageClass: "nfs-client"
    mariadb:
      replication:
        enabled: false
      master:
        persistence:
          storageClass: "nfs-client"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 1000m
  valueFileSecrets:
  - name: "bookstack-values"