---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: devops
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.drone.io
      chart: drone
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-external
      namespace: networking
  values:
    image:
        repository: drone/drone
        tag: 2.0.3
    ingress:
      enabled: true
      annotations:
          kubernetes.io/ingress.class: "external"
    persistentVolume:
      enabled: true
      storageClass: longhorn
  valuesFrom:
    - kind: Secret
      name: drone-values
      optional: false
