---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-kubernetes-secrets
  namespace: devops
spec:
  interval: 5m
  chart:
    spec:
      chart: drone-kubernetes-secrets
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    image:
        repository: drone/kubernetes-secrets
        tag: latest
    rbac:
      secretNamespace: drone-secrets
    env:
      KUBERNETES_NAMESPACE: drone-secrets
  valuesFrom:
    - kind: Secret
      name: drone-secret-provider-values
      optional: false
