---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: devops
spec:
  interval: 5m
  chart:
    spec:
      chart: drone-charts
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-external
      namespace: networking
  values:
    image:
        repository: drone/drone
        tag: 1.9.0
    ingress:
      enabled: true
      annotations:
          kubernetes.io/ingress.class: "external"
    persistentVolume:
      enabled: true
      storageClass: longhorn
  valuesFrom:
    - kind: Secret
      name: drone-values
      optional: false
