---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner-kube
  namespace: devops
spec:
  interval: 5m
  chart:
    spec:
      chart: drone-runner-kube
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: drone
      namespace: devops
    - name: drone-kubernetes-secrets
      namespace: devops
  values:
    image:
        repository: drone/drone-runner-kube
        tag: 1.0.0-beta.6
    rbac:
      buildNamespaces:
        - drone
    env:
      DRONE_NAMESPACE_DEFAULT: drone
      DRONE_RPC_HOST: drone.devops.svc
      DRONE_SECRET_PLUGIN_ENDPOINT: http://drone-kubernetes-secrets.devops.svc:3000
  valuesFrom:
    - kind: Secret
      name: drone-runner-values
      optional: false
