---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: devops
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: goharbor
        namespace: flux-system
      interval: 5m
  values:
    expose:
      type: ingress
      tls:
        certSource: none
    persistence:
      imageChartStorage:
        disableredirect: true
        type: s3
        s3:
          region: "us-east-1"
          bucket: docker-registry
    notary:
      enabled: false
    metrics:
      enabled: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64
  valuesFrom:
    - kind: Secret
      name: harbor-values
      optional: false