---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minio
  namespace: devops
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:RELEASE.*
spec:
  releaseName: minio
  helmVersion: v3
  chart:
    repository: https://helm.min.io/
    name: minio
    version: 7.0.0
  values:
    image:
      repository: jessestuart/minio
      tag: RELEASE.2020-09-02T18-19-50Z
    mcImage:
      repository: jessestuart/mc
      tag: RELEASE.2020-09-02T18-19-50Z
    helmKubectlJqImage:
      repository: drnic/kubectl
      tag: 1.16
    persistence:
      storageClass: "nfs-client"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    securityContext:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: false
  valueFileSecrets:
  - name: "minio-values"