# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   name: wekan
#   namespace: devops
#   annotations:
#     fluxcd.io/ignore: "false"
#     fluxcd.io/automated: "true"
#     fluxcd.io/tag.chart-image: 'regexp:^(version-v0\.16\.[0-9]+)$'
# spec:
#   releaseName: wekan
#   helmVersion: v3
#   rollback:
#     enable: false
#   chart:
#     git: https://github.com/wekan/wekan
#     ref: master
#     path: helm/wekan
#     version: 1.0.0
#   values:
#     service:
#       type: ClusterIP
#     ingress:
#       enabled: true
#       annotations:
#         kubernetes.io/ingress.class: "nginx"
#     autoscaling:
#       enabled: false
#     mongodb-replicaset:
#       replicas: 1
#       persistence:
#         storageClass: "nfs-client"
#     resources:
#       requests:
#         memory: 350Mi
#         cpu: 25m
#       limits:
#         memory: 500Mi
#         cpu: 1000m
#   valueFileSecrets:
#   - name: "jackett-values"