---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: wekan
  namespace: devops
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(version-2\.5\.[0-9]+)$'
spec:
  releaseName: wekan
  helmVersion: v3
  rollback:
    enable: false
  chart:
    git: https://github.com/Requarks/wiki
    ref: dev
    path: dev/helm
    version: 2.1.0
  values:
    image:
      repository: linuxserver/wikijs
      tag: version-2.5.159
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    postgresql:
      image: 
        repository: arm64v8/postgres
        tag: 9.5-alpine
      persistence:
        storageClass: "nfs-client"
      containerSecurityContext:
        runAsUser: 100
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 1000m
  valueFileSecrets:
  - name: "wikijs-values"