# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Yy/DHsnEWPvtLMgz,iv:+dHuEEu7IJcTnnb6+dOe4R89kHZEIuR1l5XIcLXotxY=,tag:7X7aoyk2XznuT8+nak8pWw==,type:str]
    SECRET_DO_EMAIL: ENC[AES256_GCM,data:JqdbBcyKJuihqtfljQ/9QBBCCX62Yz6fWi8=,iv:HP3XmifG86nH2m79klvDoLD/E+YDM4ZqpIigXZe0Qdc=,tag:NuxqYPMgPVeaE92uhYo4Mg==,type:str]
    VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:op14pjovWNGlmJtQQA13n0/gxAeL7gEIDKR1aax7TP9cJiAk43IHMiJOGxffGLA2ZaCu0sWnME4yzu2vlCJnAA==,iv:9rir4dnSx8azbceykHs3SpSHYLMNh5pFV5MVuDKgSbw=,tag:jomCkztLLzRcx2PlbsMrjg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:IVWGdUwitPnAXlS9X1OYqwyS74SRqyOCik+CNlQ9l5t2c5if1cIKwg==,iv:mIjdGCkGWEYmvOtlUO2oaG0bcMwBLNMoY92ow/JW+sg=,tag:RJVWqbc/eWj/GCEdxVZ11w==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:k92+AgXBDrrgrHFEtuclSfb+5K1r25LACO9FOH2cjGdC0eoq0J01RA==,iv:ZQBpzKXa9N+Wlpa6xho08xwowtdWNnL4zMxBjyBaROg=,tag:1ap5vFT+9Pbf7RTRb8LlXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-11T21:57:14Z"
    mac: ENC[AES256_GCM,data:qgUyjofQpEU5DOlV5wCOlDGD3U/Obg44nxl+RSfW3OY6JTJgordHpOZOeGvXz7S8hILN4aQ9BMl2mQmURTNAkUZYBk7j7/LWP1PNSKZWnROk7yUXdr7UDKn+VEkFZIGuxhnjBYNOL0yXa+Y9XG9DHY4pOdmHc57lzthSLKsoaX4=,iv:I6ZCUmNblQM38K6WNuFap3/ASQn1h2vE1xybDzLfzJM=,tag:XA8zB4+wj+jUCxNjpA5Pag==,type:str]
    pgp:
        - created_at: "2021-07-25T20:02:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1BJssYo2HXwAQ/7B3pr7d+8I1ugDKZNSjvZOGQnIj8RxiyhaRjdOdG6WIJo
            2y84AzD6ox/cUPrcZrhLfQymPGaApovQdqaNmxALfx6P0M0ilyu1Zd4n9ttOyioI
            rr+onDeT1Xbn+QlBn+QKQbmAm+gduYJ+samED6FJ5/xVZEkJW4iKpxIA7JBXiaaG
            0y3ps9+1Q6zm8FmChV/pqquepd0wnE545+X3YHqBb9hWe/1494o9GXccMF3cMchR
            rkmzpqFEfVuYX2NdFCeFJaF8GTuw0gagxULDdktuZ0y/9vToUSiJfiKWRbhwVpRP
            FhW3/oJLAJGtjzYg8VUQYQRgq5F6iTmEPi+3MeD+gqd9LWvg2NhKxgvYPv0OROTw
            U41keZ8n709zpbK7XD4nNxEvrzSKJgL2YpoYmfU3Xst8Fo5Ltj/OWBiY0uXR1CVG
            Y4rajlSSJ9cgk9lU7vsdjawXSz0mI6uBMUnr7QObJjEmHMA6kd9zTA/TVyruBNE4
            qSDHmrGfxJdQ9O/yFxrfqds2JKcPKKcSd6Z0oxgEYjuK3Pa7jpdrqffApvbJ8gCD
            lMlifj5+h/xdisLZoDM9yHWbmKM6I8g8GojRcL5T3tHe/wajPVaEjIPYEP72Vusx
            k0dwQphL2OxROZbo7P0QCj/4xOLAOJyZMbUj4SUSi18lTPtRXZyzsGgr4HwsCZzU
            aAEJAhUVzAM9tUT0PQLxm/SBY/cY2Y6mfcbDLxPlf61xmfHOugoXFeDKDpEWTRVM
            D/dgvPulBvXMD0YzNvP8OTrfnSBSBIcdKWSnp1WHrwI540AsFKjv4g6lQHe1BJqm
            50g7qFvNFh+r
            =i/j2
            -----END PGP MESSAGE-----
          fp: 6913039EDDE9EFC7E183E3A0D850142D704D4974
        - created_at: "2021-07-25T20:02:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5wFmFc/oiG7AQ/+Pl1gKMwjNkhZoO8oiOZJEOslwq/P7Fh59tFZBEXGKNBq
            C3MOxSe6dJ8Q6QB0MG4fl0vni+egblMX9s2lxAO3YPU/Md2Slpip79P9mopnpy/a
            xWZZiB88b+k6mGfDslxifJr9l67MU2wCd2Ktnxp7BUFdfSih4rEXYjDeDiq4+ZK1
            E+prUQyLmLompzHEp4qadvwoIsf9ItYlKHM5bN+uell/QMUgs8u33LRCey4sF/c8
            ZqK3OGLdNnzQgmrjEX9Pch2va92t+Wetl/m+bDJh2Boe2JeOgzqTgGyFQdvCHcJz
            6qrSsV4F738q9Shgy5mBm2kJAd9DRj9462oPsjDGf8JqehrDt6bjV02PTr1VbPIU
            TVUpIK9VPyT8A+iv2RYelCFKjoF8HkC5jPLMcgMHtLB18xmnbUj2DwL45sWPD+5M
            x1SgAAOHR6jDfOvbc08vRDZ5zD4iq2mTmMT7pqGjYjzM2nRb0aFupGV7mns8V9cA
            jnZMykoDFsCxdoyG1iz5hDIhfhyQekW+uISxoEdKZEojA1x4az8iedzLTLBUoMw0
            mBO22bA9hlvmalOUgTEFKfEgivDC6Dv4txieFfy24A9J0c7myWJbDWJ0mjBJOX9J
            rNriZDuWatIEbKkN6U4O2pOzI0wmgrtpSAJorqm1PTK8YiCqpIYmks+n5YmTPcnU
            aAEJAhV6xyVqrjsTcm7U7GIOirGVTLIYO8XEpAp8VBd0iuaS4dMeOHyEcZa7/unk
            p/1JZJQMyXZlCZa7pWhawCh9f8UOOhPv3OX+os9s/P68CdiGmIiWTP9/tH1rHP8V
            BM0DjChiMKeW
            =ZPac
            -----END PGP MESSAGE-----
          fp: 20910C1BACB162C3E050F4BA625F90997456EFA3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
