---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: "192.168.69.0/24"
  METALLB_PEER_ADDRESS: "192.168.1.1"
  METALLB_PEER_ASN: "64512"
  METALLB_ASN: "64513"
  EXTERNAL_NGINX_LB: "192.168.69.100"
  INTERNAL_NGINX_LB: "192.168.69.101"
  COREDNS_LB: "192.168.69.180"
  UNIFI_LB: "192.168.69.82"
  MQTT_LB: "192.168.69.4"
