---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cicd
  - default
  - dev
  - comms
  - flux-system
  - home
  - kube-system
  - media
  - networking
  - security
  # - system-upgrade
