---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app prowlarr
  namespace: media
spec:
  releaseName: *app
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: prowlarr
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.4.0.1802
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: http://authelia.security.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Method $request_method;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    env:
      TZ: "${TIMEZONE}"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
