---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      backupstorePollInterval: 300
      backupTarget: s3://longhorn@minio/backups
      backupTargetCredentialSecret: aws-secret
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 1
      replicaSoftAntiAffinity: true
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
  valuesFrom:
    - kind: Secret
      name: longhorn-values
      optional: false
