---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      backupstorePollInterval: 300
      backupTarget: s3://longhorn@192.168.1.50:9768/kubernetes/backups
      backupTargetCredentialSecret: aws-secret
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 2
      replicaSoftAntiAffinity: false
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
  valuesFrom:
    - kind: Secret
      name: longhorn-values
      optional: false