apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roborock
  namespace: default
spec:
  ingressClassName: internal
  rules:
  - host: "robo.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: roborock
            port:
              number: 80
  tls:
  - hosts:
    - "robo.${SECRET_DOMAIN}"
---
apiVersion: v1
kind: Service
metadata:
  name: roborock
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: roborock
  namespace: default
subsets:
  - addresses:
    - ip: 192.168.1.51
    ports:
    - port: 80
      name: http
