---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: sonarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 12.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1265
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          kubernetes.io/ingress.class: "internal"
        hosts:
          - host: "tv.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tv.${SECRET_DOMAIN"
    podSecurityContext:
      runAsGroup: 100
      runAsUser: 1000
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.50
            path: /media/tvshows
      downloads:
        enabled: true
        type: custom
        mountPath: "/downloads"
        readOnly: false
        volumeSpec:
          nfs:
            server: 192.168.1.50
            path: /downloads
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
