---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.8.1507
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.69.99
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
          nginx.ingress.kubernetes.io/proxy-body-size: 1000m
          nginx.ingress.kubernetes.io/client-body-buffer-size: 1000m
        hosts:
          - host: &host "tv.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    env:
      TZ: "${TIMEZONE}"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        type: nfs
        server: 192.168.1.50
        path: "/mnt/user/media/tvshows"
      downloads:
        enabled: true
        type: nfs
        server: 192.168.1.50
        path: "/mnt/user/downloads/"
    resources:
      requests:
        memory: 350Mi
