---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 12.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1265
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          kubernetes.io/ingress.class: "internal"
        hosts:
          - host: "tv.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tv.${SECRET_DOMAIN}"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    env:
      TZ: "America/Phoenix"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.50
            path: "/mnt/user/media/tvshows"
      downloads:
        enabled: true
        type: custom
        mountPath: "/downloads"
        readOnly: false
        volumeSpec:
          nfs:
            server: 192.168.1.50
            path: "/mnt/user/downloads"
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
