---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: devops
spec:
  releaseName: vikunja
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vikunja
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    caddy:
      noTls: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "todo.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "todo.${SECRET_DOMAIN}"
    additionalContainers:
      api:
        env:
          - name: VIKUNJA_SERVICE_TIMEZONE
            value: America/Phoenix
    env:
      TZ: "America/Phoenix"
    persistence:
      files:
        enabled: true
        existingClaim: vikunja-files
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
