---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  releaseName: frigate
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://blakeblackshear.github.io/blakeshome-charts/
      chart: frigate
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: blakeshome-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: blakeblackshear/frigate
      tag: stable-amd64
    env:
      TZ: America/Phoenix
    coral:
      enabled: true
    shmSize: 3Gi
    persistence:
      data:
        enabled: "true"
        existingClaim: frigate-config
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      hosts:
        - cctv.${SECRET_DOMAIN}
      tls:
        - hosts:
            - "cctv.${SECRET_DOMAIN}"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tpu
              operator: In
              values:
              - google-coral
    config: |
      mqtt: 
        host: eclipse-mosquitto
        topic_prefix: frigate
      database:
        path: /data/frigate.db
      detectors:
        coral:
          type: edgetpu
          device: usb
      ffmpeg:
        input_args:
          - -avoid_negative_ts
          - make_zero
          - -fflags
          - nobuffer
          - -flags
          - low_delay
          - -strict
          - experimental
          - -fflags
          - +genpts+discardcorrupt
          - -rtsp_transport
          - -use_wallclock_as_timestamps
          - "1"
      cameras:
        # ---
        porch:
          ffmpeg:
            inputs:
              - path: ${PORCH_CAMERA}
                roles:
                  - detect
                  - rtmp
          snapshots:
            enabled: true
          height: 2160
          width: 3840
          fps: 5
        garage:
          ffmpeg:
            inputs:
              - path: "${GARAGE_CAMERA}"
                roles:
                  - detect
                  - rtmp
          snapshots:
            enabled: true
          height: 2160
          width: 3840
          fps: 5
        backyard_pathway_1:
          ffmpeg:
            inputs:
              - path: ${BACKYARD_PATHWAY_CAMERA_1}
                roles:
                  - detect
                  - rtmp
          snapshots:
            enabled: true
          height: 2160
          width: 3840
          fps: 5
        side_alley_1:
          ffmpeg:
            inputs:
              - path: ${SIDE_ALLEY_CAMERA_1}
                roles:
                  - detect
                  - rtmp
          snapshots:
            enabled: true
          height: 2160
          width: 3840
          fps: 5
        side_alley_2:
          ffmpeg:
            inputs:
              - path: ${SIDE_ALLEY_CAMERA_2}
                roles:
                  - detect
                  - rtmp
          snapshots:
            enabled: true
          height: 2160
          width: 3840
          fps: 5 
