---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.9.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: postgres
      tag: 13.3-alpine
      pullPolicy: IfNotPresent
    postgresqlUsername: postgres
    postgresqlPassword: ${SECRET_POSTGRES_PASSWORD}
    persistence:
      enabled: true
      existingClaim: postgres-data