apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # see the "Cluster Settings" section below for more details on which image of ceph to run
    image: quay.io/ceph/ceph:v16.2.6
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  placement:
    all:
      tolerations:
        - operator: "Exists"
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    port: 7000
    ssl: false
  storage:
    useAllNodes: false
    useAllDevices: false
    onlyApplyOSDPlacement: false
    config:
      osdsPerDevice: "1"
    nodes:
      - name: "k8s-phoenix"
        devices:
          - name: sdf
          - name: sde
      - name: "k8s-odin"
        devices:
          - name: sda
          - name: sdc