---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrone-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
