---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  releaseName: navidrome
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: navidrome
      version: 6.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: deluan/navidrome
      tag: 0.47.5
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "music.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "music.${SECRET_DOMAIN}"
    env:
      TZ: "America/Phoenix"
    persistence:
      config:
        enabled: true
        existingClaim: navidrone-data
      music:
        enabled: true
        existingClaim: nfs-media-music-pvc
