---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.27.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    configuration:
      extraEnvVars:
        TZ: "America/Phoenix"
      provider: aws
      backupStorageLocation:
        name: default
        bucket: backup-velero
        config:
          region: home
          s3ForcePathStyle: true
          s3Url: ${MINIO_URL}
      volumeSnapshotLocation:
        name: aws
        config:
          region: home
      resticTimeout: 6h
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.4.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    snapshotsEnabled: false
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
    schedules:
      bi-daily-backup:
        schedule: "0 6,18 * * *"
        template:
          ttl: "120h"
    metrics:
      enabled: false
    kubectl:
      image:
        repository: kubesphere/kubectl
        tag: v1.22.0
    upgradeCRDs: false
    cleanUpCRDs: false
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id = $MINIO_ACCESS_KEY
          aws_secret_access_key = $MINIO_SECRET_KEY
