---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: ${BOOTSTRAP_METALLB_LB_RANGE}
  METALLB_PEER_ADDRESS: ${BOOTSTRAP_METALLB_PEER_ADDRESS}
  METALLB_PEER_ASN: ${BOOTSTRAP_METALLB_PEER_ASN}
  METALLB_ASN: ${BOOTSTRAP_METALLB_ASN}
  INTERNAL_NGINX_LB: ${BOOTSTRAP_INTERNAL_NGINX_LB}
