---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: dev
spec:
  interval: 1h
  chart:
    spec:
      chart: harbor
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 1h
  values:
    expose:
      tls:
        # The ingress controller has a default certificate so we don't need to configure it
        certSource: none
      ingress:
        className: nginx
        hosts:
          core: harbor.${SECRET_DOMAIN}
    externalURL: https://harbor.${SECRET_DOMAIN}
    harborAdminPassword: ${SECRET_HARBOR_ADMIN}

    trivy:
      enabled: false
    chartmuseum:
      enabled: false
    notary:
      enabled: false

    portal:
      nodeSelector:
        kubernetes.io/arch: amd64
    core:
      nodeSelector:
        kubernetes.io/arch: amd64
    jobservice:
      nodeSelector:
        kubernetes.io/arch: amd64
    registry:
      nodeSelector:
        kubernetes.io/arch: amd64
    database:
      internal:
        nodeSelector:
          kubernetes.io/arch: amd64
    redis:
      internal:
        nodeSelector:
          kubernetes.io/arch: amd64
    exporter:
      nodeSelector:
        kubernetes.io/arch: amd64

    persistence:
      enabled: true
      imageChartStorage:
        type: s3
        s3:
          region: us-west-1
          bucket: docker-registry
          regionendpoint: ${SECRET_MINIO_URL}
          accesskey: ${SECRET_ACCESS_KEY}
          secretkey: ${SECRET_SECRETKEY}
