---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: internal-nginx
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  values:
    controller:
#      watchIngressWithoutClass: true
      ingressClassByName: true
      ingressClassResource:
        name: internal
        enabled: true
        default: false
        controllerValue: "k8s.io/internal-ingress-nginx"
      replicaCount: 1
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      publishService:
        enabled: true
      service:
        type: LoadBalancer
        loadBalancerIP: "${INTERNAL_NGINX_LB}"
        externalTrafficPolicy: Local
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-proxy-protocol: "false"
        proxy-body-size: "100m"
        use-forwarded-headers: "true"
        proxy-ignore-client-abort: "on"
        proxy-request-buffering: "off"
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      extraArgs:
        default-ssl-certificate: "networking/${SECRET_DOMAIN/./-}-tls"
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
