---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  releaseName: influxdb
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb2
      version: 2.0.12
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: influxdb
      tag: 2.2.0-alpine
    service:
      type: LoadBalancer
      loadBalancerIP: "${INFLUXDB_LB}"
      externalTrafficPolicy: Local
    adminUser:
      retention_policy: "12w"
      password: "${INFLUXDB_PASSWORD}"
    persistence:
      enabled: "true"
      useExisting: true
      name: influxdb-data
