---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/zwave-js/zwave-js-ui
      tag: 9.6.2

    env:
      TZ: "${TIMEZONE}"

    service:
      main:
        ports:
          http:
            port: &port 8091
          websocket:
            enabled: true
            port: 3000

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "zwave.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    securityContext:
      privileged: true

    persistence:
      config:
        enabled: true
        existingClaim: zwavejs-config
        mountPath: /usr/src/app/store
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_6120113C-if00-port0
        hostPathType: CharDevice

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: usb
                  operator: In
                  values:
                    - zwave

    # resources:
    #   requests:
    #     memory: 200Mi
    #     cpu: 50m
    #   limits:
    #     memory: 500Mi

    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
