apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: home
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
  type: ClusterIP
  selector:
    app: postgres