# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   name: wikijs
#   namespace: devops
#   annotations:
#     fluxcd.io/ignore: "false"
#     fluxcd.io/automated: "true"
#     fluxcd.io/tag.chart-image: 'regexp:^(version-2\.5\.[0-9]+)$'
# spec:
#   releaseName: wikijs
#   helmVersion: v3
#   rollback:
#     enable: false
#   chart:
#     git: https://github.com/Requarks/wiki
#     ref: dev
#     path: dev/helm
#     version: 2.1.0
#   values:
#     image:
#       repository: requarks/wiki
#       tag: 2.5
#     ingress:
#       enabled: true
#       annotations:
#         kubernetes.io/ingress.class: "nginx"
#     postgresql:
#       image: 
#         repository: arm64v8/postgres
#         tag: 9.5-alpine
#       persistence:
#         storageClass: "nfs-client"
#         mountPath: /var/lib/postgresql
#       securityContext:
#         runAsUser: 70
#       containerSecurityContext:
#         runAsUser: 70
#       postgresqlDataDir: /var/lib/postgresql/data
#     resources:
#       requests:
#         memory: 350Mi
#         cpu: 25m
#       limits:
#         memory: 500Mi
#         cpu: 1000m
#   valueFileSecrets:
#   - name: "wikijs-values"