---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  releaseName: calibre-web
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/calibre-web
      tag: version-0.6.11
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "read.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "read.${SECRET_DOMAIN}"
    env:
      TZ: "America/Phoenix"
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config
      books:
        enabled: true
        type: pvc
        existingClaim: nfs-media-books-pvc
        subPath: "calibre/Calibre Library"
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
