---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.authelia.com
      chart: authelia
      version: 0.8.38
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: 4.36.2
    domain: "${SECRET_DOMAIN}"
    pod:
      env:
        - name: TZ
          value: "${TIMEZONE}"
    ingress:
      enabled: true
      className: nginx
      tls:
        enabled: true
        secret: authelia-cert
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      subdomain: auth
    configMap:
      enabled: true
      access_control:
        default_policy: one_factor
      storage:
        postgres:
          enabled: true
          host: authelia-postgresql-postgresql
          port: 5432
          database: authelia
          username: authelia
          ssl:
            mode: disable
      session:
        redis:
          enabled: true
          enabledSecret: true
          username: ""
          host: authelia-redis
          port: 6379
          database_index: 0
      authentication_backend:
        password_reset:
          disable: false
        ldap:
          implementation: custom
          url: "ldap://${NFS_SERVER}:3890"
          username_attribute: uid
          additional_users_dn: ou=people
          additional_groups_dn: ou=groups
          base_dn: ${SECRET_LDAP_BASE_DN}
          user: uid=${SECRET_LDAP_ADMIN_USERNAME},ou=people,${SECRET_LDAP_BASE_DN}
          users_filter: "(&({username_attribute}={input})(objectClass=person))"
          groups_filter: "(member={dn})"
      notifier:
        smtp:
          enabled: true
          enabledSecret: true
          username: ${SECRET_SMTP_USER}
          host: ${SECRET_SMTP_HOST}
          port: 587
          sender: ${SECRET_SMTP_USER}
          identifier: localhost
          subject: "[Authelia] {title}"
          startup_check_address: ${SECRET_SMTP_USER}
    secret:
      ldap:
        key: LDAP_PASSWORD
        value: ${SECRET_LDAP_ADMIN_PASSWORD}
      smtp:
        key: SMTP_PASSWORD
        value: ${SECRET_SMTP_PASSWORD}
      storage:
        key: STORAGE_PASSWORD
        value: ${SECRET_AUTH_POSTGRES_PASSWORD}
      redis:
        key: REDIS_PASSWORD
        value: ${SECRET_AUTH_REDIS_PASSWORD}
