---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-postgresql
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.6.24
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  # values yaml: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
  values:
    auth:
      username: "authelia"
      database: "authelia"
      password: ${SECRET_AUTH_POSTGRES_PASSWORD}
      postgresPassword: ${SECRET_AUTH_POSTGRES_PASSWORD}
    metrics:
      enabled: false
    primary:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      persistence:
        enabled: true
        storageClass: ceph-block
