---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-db
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zalando-postgres-cluster
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/stable/zalando-postgres-cluster/values.yaml
  values:
    postgresql:
      users:
        postgres:
          - superuser
          - createdb
      databases:
        tt-rss: postgres
      postgresql:
        version: "13"
      volume:
        storageClass: ceph-block
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
    superuser:
      user: authelia
      password: ${STORAGE_PASSWORD}
