# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: security
stringData:
    LDAP_BASE_DN: ENC[AES256_GCM,data:O0w8CfCALNjUA3yZSM6nzQbO,iv:jTX9SqaI2PZtmAXstz7e4VNmMw87w4MJLXxSh4shsTk=,tag:PAz2/zcd1+1Fi8WILy4suQ==,type:str]
    LDAP_ADMIN_USERNAME: ENC[AES256_GCM,data:lwu7Y8MsLDg=,iv:szIjQumk6f+Icr/0UUSq7/b6GFzs1yr/G05gdgiFPBo=,tag:i2Zrbn5uuxJlvXTKRJ0sBw==,type:str]
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:kdCHxYfS0RrPBYNyNqgMztI=,iv:xPB5KXcgTvLqQRGwkbUD3qm/VeMXHhhIB6y5pZceZc8=,tag:F1fbZsK3ZLnbcCvLXPYT7Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:EattPiecWOgBqO0tSzxnK701KK67VqSzcAo1,iv:ljrDTPxZfvggRFA5hYm7QaL8EMj5FRwgKLUViP8ndy8=,tag:245tPKvKVj1l0JBo8GzzoQ==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:2fDT9O5amubOe5A9XO8TXXkBNsEHQWaQXy/+,iv:63vBX20tX/ko6aMa4ZDqorkndCSkcyGigvYXWCRGg+w=,tag:u4grb9Kys5qwc88oX3qEAA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:4TN9MbCxctey/DzSh9eLPwiCiYjTKyD+AuE=,iv:jiKDlOzVljl71nMdaw3zgdhbH0KxhPItvf3IGyXN8Hc=,tag:rr720cvVGt6iL0Tw098y2g==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:jaVKBOG80zS66dwFAh2KwOLoZYWIJtHaH7gvjR904lXbcpeOajcZOkxey4I7Ja/f83s=,iv:MChRaBDfPcntkbSGbtmU4/L9nYxsxvs+uTjqJwr4Og0=,tag:7WTufYYe4mzYLMaVVmYYaA==,type:str]
    SMTP_DOMAIN: ENC[AES256_GCM,data:RIgd2fBxPc3iaLkXczqq/A==,iv:HDEpUKY+vp2cIAc/84o0XRI21JFTR4BJIfNGRRbfa5Q=,tag:4yvMUSfb92E3+4MRUBaDCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzj03r3dv3xrvtns0v0ufs4pvchw3u0564u36hc5h3vmxqu3gkq3wmu9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcFI3SmUyeTNoZkY2MUNz
            bjEyTkFZaGcvN3hYbFcrblMrMlR6SjdNV3o0ClVvakp2N0VFYjlXQStvY3JDYkoy
            R25vK0YwNklteTZHVEpkRXBSeThOTGcKLS0tIERvenZVazBsbHg0dHBaQ042Slky
            RnpOUGdqb1M1NHBoZllIeWZib1FReDgK8Io0oNOSDE5Aoa1XRSGQFXdJK+NtolrE
            yJ1dx9Tj4cSSQx8fR3ikSLxbmLhZL/YyYMu+EJ42u5L7DGf6Vl5BHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-15T18:53:19Z"
    mac: ENC[AES256_GCM,data:GZy18DFVmqE7LpqjH6ZngzSwv7qXirBLj8+JOAgF8i+RnTqWXAWwTKA/Xoledc75QYTmNptJ4o9n2LaZk1Od/L+8sExccN4QJmkp3znkeJu2qPladcAC/uhRgYKDQhzxDmO2fBICfrucnHrzDYpzxsrgZ7KD2DVirPGaNu8u0wE=,iv:ki37XVZmtdklGLnAHxNq/gQe3GFhAFCoCfDooIfWtPU=,tag:PUfWbH7XUT57MnxKygb1JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
