# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: security
stringData:
    JWT_TOKEN: ENC[AES256_GCM,data:xbafw5b++UYewQ+T+uNs8LCQ5Yq6eFEjGIt0,iv:mplLGItjwZMa1aYfwGR9p9WM8EP33BfTol0Sp9xQZug=,tag:wMOBwHJT67vs4VoIsn2S9g==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:c6Wa4qy/UTKr/33oWV1jy/kt6++62+XC2s9qYfsW7PDTcUZiNe/rEljXW/Y6+jkT6G4sCGvQ,iv:EhmIcKvHMpAQYTzFCHLIKo18koWzkmL/F1E7ETiUlsc=,tag:xZZrU/AON7DsY3SpN5iWdA==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:jDY+jOpWLUITgU7hVemixnt+azCm3exiGBwdj6E579pebw0ROPiq4iSJCQ1oVFVoYfCO7tbs,iv:Zv+mesus+ce5H9PvQkjZgN0dd/A9VIiVIIZRWnHu4yM=,tag:TPmjLnNKQ4U006VbXtuViQ==,type:str]
    DUO_API_KEY: ENC[AES256_GCM,data:N4dPxugm8eRJyRtybAa7akcpKWyVAv7YYhUDUJBoSv9xOxNWJrj4U2fPSFX8LHaArP/wUvOa,iv:jYU+t9V71NNZkWarJEZnW/FOcSAQuUnGtyzZix3XHy4=,tag:SnXug95uMX5W2b1Zt/EuFg==,type:str]
    REDIS_SENTINEL_PASSWORD: ENC[AES256_GCM,data:qN+NeR72s4hgOsus83XkbMUAmxKiqNPXKu4XwaCxHvT0Kryjr27ViqGzwPXi+L5dOIZu818t,iv:tE68LB1tCEKhXNcgeitkNRBOwgGMesYDANude/h5iHo=,tag:TMuA5m/EKqd/Q52N8rCQ9A==,type:str]
    OIDC_PRIVATE_KEY: ENC[AES256_GCM,data:Lt1whfng8wjCYJv/mcgBQJ+bpi6O7cSlmsSPPQiX0U7ZTH8jfsGaVyAJWuNMNjFj8mEIzjVE,iv:QsYLpb/jqwJKWnl9TuQiFk0XD6C78+ImNSkjadIdb18=,tag:AfyKhGnKniKxypvDOK1Zfg==,type:str]
    OIDC_HMAC_SECRET: ENC[AES256_GCM,data:wGKPBvqrms3GJnQq0JhbA8rfhjKIINiE9aDVMPGgui/pFC7cXtIUCNLqKR+HjnFnz++sjO8s,iv:N5b3MJCABPb9W1NRl5UlwW+XSUJ89mKpjg9CpLHiF6Y=,tag:j/8KSEo8Iea3TQB0///MRA==,type:str]
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:sapzSDUDKX1DQ30vKhP3U5o=,iv:s8iGSqFdz0AuiZOyu8/6jSg8JIvIw+vwuUVR4RrY7tU=,tag:wjCs2+8VDVH+aYVb5jCEYQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:u0E1NvcR+3IgIq6I1XHijnB4MqL6c6emf8gq,iv:Jqylj7jXG23zI3B6g6+Nnyuy4o0Ya8MWsmxrNk3SAbM=,tag:JShVbkvPZZ76Q1iA1vx0AA==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:vJCLoaqIPZ8nojJONVL9lRazMjLU1RaAsSI=,iv:SwQw6XFKtc4iZTLwEOSkmu+GeM+fmlb66jQCfd0I2pc=,tag:WYKSXmYBZXokmwW3YZlODQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:W0F91Syce+mtcpE1g58HlfFMrNMo2xZn64hg59mvKRl1k5j7qbDwkAsL2cMRgg98hXo=,iv:7CNkkjznwLcA1QqmqIn/XYhD6QHTkIWsqfwku7e11ds=,tag:KMMLhVhzYxAPFFm/OJkJ2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzj03r3dv3xrvtns0v0ufs4pvchw3u0564u36hc5h3vmxqu3gkq3wmu9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bUxLbG8wbVhWYmR0UGhn
            Qm42VjhjNTdlcHFEaEJOOHhuTEhESnp2YkNzCjAzUThMNjU5V2hmMTNvZUdrdlFj
            ODNacnd3SWhMQWJXQmZ6M3g5bWg1RmcKLS0tIC91dFJscFcvNkEyMkk5NUJ4T0lz
            aHNWZkE3WlZjaHJUWkNCaXlEaVJGRFUK5iCp/M2NLX8NfKvogz4p237YqNaKPOox
            n7P9BHKPrCW4J7ZaDnIMkIgdIG7M7hD+aTXZ3D4Zz9Il0KiCsNd1Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T00:33:02Z"
    mac: ENC[AES256_GCM,data:jC3pcSEOW7trLNUxv8zOSL5ONvhs+i5NGNO12vuYFmEiipFXVYMSgMzgSMphGTBK2tKz+m5Gl9oDMZosRHFqAtPDDmBOSvo0QpMh30pkfsjuTcCDqd+QOpi5jVJosnhn5lbB6otyhcq3br5yiuRSQLFWH+oIY/cqAJnrDsRP//I=,iv:oz1VK7aTcPqt+NPApyJ/NTEvIwxDNFjN7BuvIbX6djA=,tag:DAS7ArWZORknZ2x0OxZgLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
