---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  releaseName: bazarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v0.9.5
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          kubernetes.io/ingress.class: "internal"
    env:
      TZ: "America/Phoenix"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
      media:
        enabled: true
        existingClaim: nfs-media-movies-pvc
      tv:
        enabled: true
        type: custom
        mountPath: "/tv"
        readOnly: false
        volumeSpec:
          name: tv
          persistentVolumeClaim:
            claimName: nfs-media-tv-pvc
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: bazarr-values
      optional: false
