---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  releaseName: calibre-web
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: linuxserver/calibre-web
      tag: version-0.6.11
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    env:
      TZ: "America/Phoenix"
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
      books:
        enabled: true
        mountPath: /books
        existingClaim: nfs-media-books-pvc
    resources:
      requests:
        memory: 150Mi
        cpu: 25m
      limits:
        memory: 350Mi
  valuesFrom:
    - kind: Secret
      name: calibre-web-values
      optional: false
