---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  releaseName: calibre-web
  interval: 5m
  chart:
    spec:
      chart: calibre-web
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/calibre-web
      tag: version-0.6.11
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      TZ: "America/Phoenix"
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
      books:
        existingClaim: nfs-media-books-pvc
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 100m
  valuesFrom:
    - kind: Secret
      name: calibre-web-values
      optional: false