---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(version-0\.6\.[0-9]+)$'
spec:
  releaseName: calibre-web
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: calibre-web
    version: 2.0.1
  values:
    image:
      repository: linuxserver/calibre-web
      tag: version-0.6.9
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Phoenix"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        size: 1Gi
      books:
        existingClaim: nfs-media-books-pvc
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 1000m
  valueFileSecrets:
  - name: "calibre-web-values"