---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(version-v0\.16\.[0-9]+)$'
spec:
  releaseName: jackett
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jackett
    version: 3.0.1
  values:
    image:
      repository: linuxserver/jackett
      tag: version-v0.16.2284
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/Phoenix"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        size: 1Gi
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 1000m
  valueFileSecrets:
  - name: "jackett-values"