---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  releaseName: jackett
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: ghcr.io/k8s-at-home/jackett
      tag: v0.17.931
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    timezone: "America/Phoenix"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
    resources:
      requests:
        memory: 250Mi
        cpu: 10m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: jackett-values
      optional: false
