---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  releaseName: jackett
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: linuxserver/jackett
      tag: version-v0.17.668
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    timezone: "America/Phoenix"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
    resources:
      requests:
        memory: 250Mi
        cpu: 10m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: jackett-values
      optional: false