---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: lazylibrarian
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    #fluxcd.io/tag.chart-image: 'regexp:^(version-v0\.16\.[0-9]+)$'
spec:
  releaseName: lazylibrarian
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://raw.githubusercontent.com/aldoborrero/k8s-usenet/master/charts/
    name: lazylibrarian
    version: 1.0.0
  values:
    image:
      repository: linuxserver/lazylibrarian
      tag: version-63b212b5
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    lazylibrarian:
      tz: "America/Phoenix"
      puid: 99
      pgid: 100
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        size: 1Gi
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
      books:
        enabled: true
        existingClaim: nfs-media-books-pvc
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 1000m
  valueFileSecrets:
  - name: "lazylibrarian-values"