---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  releaseName: lidarr
  interval: 5m
  chart:
    spec:
      chart: lidarr
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/lidarr
      tag: nightly-version-0.8.0.2062
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        size: 5Gi
        storageClass: longhorn
      media:
        enabled: true
        existingClaim: nfs-media-music-pvc
    additionalVolumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-media-downloads-pvc
    additionalVolumeMounts:
      - name: downloads
        mountPath: "/downloads"
    resources:
      requests:
        memory: 350Mi
        cpu: 80m
      limits:
        memory: 700Mi
  valuesFrom:
    - kind: Secret
      name: lidarr-values
      optional: false