---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  releaseName: lidarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lidarr
      version: 8.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v0.8.1.2132
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    podSecurityContext:
      runAsGroup: 100
      runAsUser: 1000
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClass: longhorn
      media:
        enabled: true
        existingClaim: nfs-media-music-pvc
    additionalVolumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-media-downloads-pvc
    additionalVolumeMounts:
      - name: downloads
        mountPath: "/downloads"
    resources:
      requests:
        memory: 350Mi
        cpu: 80m
      limits:
        memory: 700Mi
  valuesFrom:
    - kind: Secret
      name: lidarr-values
      optional: false
