---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: lidarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: lidarr
    version: 4.0.1
  values:
    lidarr:
      image:
        organization: linuxserver
        repository: lidarr
        tag: latest
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      env:
        TZ: "America/Phoenix"
        PUID: "1000"
        PGID: "100"
      persistence:
        type: statefulset
        config:
          enabled: true
          size: 250Mi
        media:
          enabled: false
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 1000Mi
  valueFileSecrets:
  - name: "lidarr-values"