---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    #fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: ombi
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: ombi
    version: 5.8.0
  values:
    image:
      repository: linuxserver/ombi
      tag: v4-preview
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valueFileSecrets:
  - name: "ombi-values"