---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
spec:
  releaseName: ombi
  interval: 5m
  chart:
    spec:
      chart: ombi
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/ombi
      tag: v4-preview
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valuesFrom:
    - kind: Secret
      name: ombi-values
      optional: false