---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  releaseName: overseerr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: sctx/overseerr
      tag: 1.24.0
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
    resources:
      requests:
        memory: 150Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: overseerr-values
      optional: false
