---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  releaseName: prowlarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: prowlarr
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.1.0.325
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    env:
      TZ: "America/Phoenix"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
    resources:
      requests:
        memory: 250Mi
        cpu: 10m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: prowlarr-values
      optional: false
