---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  releaseName: qbittorrent
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.4.1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    timezone: "America/Phoenix"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
      shared:
        enabled: true
        emptyDir:
          enabled: true
        mountPath: /shared
    addons:
      vpn:
        enabled: true
        type: openvpn
        env:
          FIREWALL: 'on'
        scripts:
          up: |-
            #!/bin/bash
            /etc/openvpn/up.sh
            echo "connected" > /shared/vpnstatus

          down: |-
            #!/bin/bash
            /etc/openvpn/down.sh
            echo "disconnected" > /shared/vpnstatus
    resources:
      requests:
        memory: 250Mi
        cpu: 10m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: qbittorrent-values
      optional: false
