---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
   # fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: qbittorrent
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: qbittorrent
    version: 5.0.0
  values:
    qbittorrent:
      image:
        organization: linuxserver
        repository: qbittorrent
        tag: arm64v8-latest
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      env:
        TZ: "America/Phoenix"
        PUID: "1000"
        PGID: "100"
      persistence:
        type: statefulset
        config:
          enabled: true
          storageClass: "nfs-client"
          size: 1Gi
        downloads:
          enabled: false
      additionalVolumes:
        - name: qbittorrent-scripts
          configMap:
            name: qbittorrent-custom-scripts
            defaultMode: 511
        - name: downloads
          persistentVolumeClaim:
            claimName: nfs-media-downloads-pvc
        - name: shared
          emptyDir: {}
      openvpn:
        enabled: true
        image: 
          tag: aarch64
        scripts:
          up: |-
            #!/bin/bash
            /etc/openvpn/up.sh
            echo "connected" > /shared/vpnstatus
          down: |-
            #!/bin/bash
            /etc/openvpn/down.sh
            echo "disconnected" > /shared/vpnstatus
        additionalVolumeMounts:
          - mountPath: /shared
            name: shared
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ $(curl -s https://ipinfo.io/country) == "US" ]; then exit 0; else exit $?; fi
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 1
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 1000Mi
  valueFileSecrets:
  - name: "qbittorrent-values"