---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: radarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 11.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v3.0.2.4552
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    podSecurityContext:
      runAsGroup: 100
      runAsUser: 1000
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
      media:
        enabled: true
        existingClaim: nfs-media-movies-pvc
    additionalVolumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-media-downloads-pvc
    additionalVolumeMounts:
      - name: downloads
        mountPath: "/downloads"
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: radarr-values
      optional: false
