---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    #fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 6.0.1
  values:
    radarr:
      image:
        organization: linuxserver
        repository: radarr
        tag: 3.0.0.3860-ls25
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      env:
        TZ: "America/Phoenix"
        PUID: "1000"
        PGID: "100"
      persistence:
        type: statefulset
        config:
          enabled: true
          size: 1Gi
        media:
          enabled: true
          existingClaim: nfs-media-movies-pvc
      # additionalVolumes:
      #   - name: downloads
      #     persistentVolumeClaim:
      #       claimName: nfs-media-downloads-pvc
      # additionalVolumeMounts:
      #   - name: downloads
      #     mountPath: "/downloads"
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 1000Mi
  valueFileSecrets:
  - name: "radarr-values"