---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: radarr
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/radarr
      tag: nightly-version-3.1.0.4634
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
      media:
        enabled: true
        existingClaim: nfs-media-movies-pvc
    additionalVolumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-media-downloads-pvc
    additionalVolumeMounts:
      - name: downloads
        mountPath: "/downloads"
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: radarr-values
      optional: false