---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 12.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1265
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          kubernetes.io/ingress.class: "internal"
    podSecurityContext:
      runAsGroup: 100
      runAsUser: 1000
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
      media:
        enabled: true
        existingClaim: nfs-media-tv-pvc
      downloads:
        enabled: true
        type: custom
        mountPath: "/downloads"
        readOnly: false
        volumeSpec:
          name: downloads
          persistentVolumeClaim:
            claimName: nfs-media-downloads-pvc
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - k8s-summoner
    resources:
      requests:
        memory: 350Mi
        cpu: 100m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: sonarr-values
      optional: false
