---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 9.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    image:
      repository: linuxserver/sonarr
      tag: preview-version-3.0.5.1143
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    env:
      TZ: "America/Phoenix"
      PUID: "1000"
      PGID: "100"
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
      media:
        enabled: true
        existingClaim: nfs-media-tv-pvc
    additionalVolumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-media-downloads-pvc
    additionalVolumeMounts:
      - name: downloads
        mountPath: "/downloads"
    resources:
      requests:
        memory: 350Mi
        cpu: 100m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: Secret
      name: sonarr-values
      optional: false