---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    #fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: sonarr
    version: 6.0.1
  values:
    sonarr:
      image:
        organization: linuxserver
        repository: sonarr
        tag: preview-3.0.4.1061-ls25
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      env:
        TZ: "America/Phoenix"
        PUID: "1000"
        PGID: "100"
      persistence:
        type: statefulset
        config:
          enabled: true
          size: 1Gi
        media:
          enabled: true
          existingClaim: nfs-media-tv-pvc
      additionalVolumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: nfs-media-downloads-pvc
      additionalVolumeMounts:
        - name: downloads
          mountPath: "/downloads"
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 1000Mi
  valueFileSecrets:
  - name: "sonarr-values"