---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-podcasts-pv
spec:
  storageClassName: nfs-media-podcasts
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER}
    path: "/mnt/user/media/podcasts"
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
