apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: rook-ceph-block