apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-static-pvc
  namespace: recipes
spec:
  resources:
    requests:
      storage: "1Gi"
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn