apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recipes
  namespace: recipes
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: recipes
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: postgres-recipes
  # See https://github.com/k8s-at-home/charts/blob/master/charts/recipes/values.yaml
  values:
    image:
      repository: vabene1111/recipes
      tag: 0.16.6    
    persistence:
      media:
        enabled: true
        existingClaim: recipes-media-pvc
      static:
        enabled: true
        existingClaim: recipes-static-pvc    
    env:
      DEBUG: "0"
      ALLOWED_HOSTS: "*"
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      #DB_OPTIONS: '{"sslmode":"require"}'
      POSTGRES_HOST: postgres-recipes-postgresql
      POSTGRES_PORT: "5432"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      TIMEZONE: "America/Phoenix"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/proxy-body-size: "8000m"
      #  nginx.ingress.kubernetes.io/auth-url: "https://ingress-auth.${CLUSTER_DOMAIN}/auth"
      #  nginx.ingress.kubernetes.io/auth-signin: "https://ingress-auth.${CLUSTER_DOMAIN}/start?rd=$scheme://$host$request_uri"
        ingress.kubernetes.io/ssl-redirect: "true"
    additionalContainers:
    - name: nginx
      image: nginx:1.20.0
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
      #
      # If persistent volumes are enabled ; please uncomment the following lines
      #
      - name: media
        mountPath: '/media'
      - name: static
        mountPath: '/static'
      - name: recipes-config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx-config
        readOnly: true

  valuesFrom:
  - kind: Secret
    name: recipes-values
    optional: false
