---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: security
spec:
  releaseName: keycloak
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 9.6.2
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: alemairebe/keycloak
      tag: 12.0.3
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    postgresql:
      enabled: true
      image:
        repository: postgres
        tag: 9.5-alpine
      persistence:
        enabled: true
        storageClass: longhorn
        mountPath: /var/lib/postgresql
      securityContext:
        runAsUser: 70
      containerSecurityContext:
        runAsUser: 70
      postgresqlDataDir: /var/lib/postgresql/data
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
  valuesFrom:
    - kind: Secret
      name: keycloak-values
      optional: false