---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: security
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(version-0\.6\.[0-9]+)$'
spec:
  releaseName: keycloak
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://codecentric.github.io/helm-charts
    name: keycloak
    version: 9.6.2
  values:
    image:
      repository: alemairebe/keycloak
      tag: 11.0.3
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    postgresql:
      enabled: false
      image:
        repository: postgres
        tag: 9.6-alpine
      persistence:
        enabled: true
        storageClass: "nfs-client"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 1000m