---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: phpldapadmin
  namespace: security
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(version-0\.6\.[0-9]+)$'
spec:
  releaseName: phpldapadmin
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://cetic.github.io/helm-charts
    name: phpldapadmin
    version: 0.1.4
  values:
    image:
      tag: 0.9.0
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 1000m
  valueFileSecrets:
  - name: "phpldapadmin-values"