---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: phpldapadmin
  namespace: security
spec:
  releaseName: phpldapadmin
  interval: 5m
  chart:
    spec:
      chart: phpldapadmin
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: cetic
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    image:
      tag: stable
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 1000m
  valuesFrom:
    - kind: Secret
      name: phpldapadmin-values
      optional: false