---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: security
spec:
  releaseName: vaultwarden
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: networking
  values:
    nameOverride: vaultwarden
    fullnameOverride: vaultwarden
    image:
      repository: vaultwarden/server
      tag: 1.21.0-alpine
    env:
      SIGNUPS_ALLOWED: true
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "internal"
          kubernetes.io/tls-acme: "true"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
  valuesFrom:
    - kind: Secret
      name: vaultwarden-values
      optional: false
