---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.12.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    deploymentStrategy:
      type: Recreate
    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
    grafana.ini:
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth.basic:
        disable_login_form: false
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-operated:9090
          access: proxy
        - name: influxdb-pfsense
          type: influxdb
          access: proxy
          url: http://influxdb:8086
        - name: influxdb-home-assistant
          type: influxdb
          access: proxy
          url: http://influxdb:8086
        - name: influxdb-unraid-tower
          type: influxdb
          access: proxy
          url: http://influxdb:8086
    dashboards:
      default:
        nginx-dashboard:
          url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
          datasource: Prometheus
        pfsense-dashboard:
          url: https://raw.githubusercontent.com/VictorRobellini/pfSense-Dashboard/master/pfSense-Grafana-Dashboard.json
          datasource: influxdb-pfsense
        unraid-tower-dashboard:
          gnetId: 7233
          revision: 1
          datasource: influxdb-unraid-tower
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
    - natel-discrete-panel
    - pr0ps-trackmap-panel
    - grafana-piechart-panel
    - vonage-status-panel
    - grafana-worldmap-panel
    - grafana-clock-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi
      accessModes:
      - ReadWriteOnce
    podAnnotations:
      configmap.reloader.stakater.com/reload: "grafana"
  valuesFrom:
    - kind: Secret
      name: grafana-values
      optional: false
