---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  releaseName: influxdb
  interval: 5m
  chart:
    spec:
      chart: influxdb
      version: 4.8.12
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: metallb
      namespace: kube-system
  values:
    image:
      repository: influxdb
      tag: 2.0.4
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.69.120
      externalTrafficPolicy: Local
    persistence:
      enabled: true
      size: 50Gi
      storageClass: longhorn
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 6
      periodSeconds: 5
    config:
      opentsdb:
        enabled: true