---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  releaseName: influxdb
  interval: 5m
  chart:
    spec:
      chart: influxdb
      version: 4.8.12
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: influxdb
      tag: 1.8.2
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.80
    persistence:
      enabled: true
      size: 50Gi
      storageClass: longhorn
    resources:
      requests:
        memory: 512Mi
        cpu: 2
      limits:
        memory: 1000Mi
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 6
      periodSeconds: 5
    config:
      opentsdb:
        enabled: true