# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: frigate
    namespace: home
stringData:
    PORCH_CAMERA: ENC[AES256_GCM,data:KZrZEwNcP+JqlHvjvcJQ8LslcaN+zVftmTcmmcx0fW6LG8kzwIBxZQJ5jpCF9XpIMHf8P9nD//nbGVAg8OyW/7EcS/+hDyhDr3rb3sXjgqhdYNin7onotmPy40CmVaQ=,iv:Tj2xlpctgy28UzQmHKIow9pdspvkpAQOFTKZ6cPsUi4=,tag:m7/+TAWMcJPnzFnzyBNljA==,type:str]
    GARAGE_CAMERA: ENC[AES256_GCM,data:1MaPOIF89a7ynaBLxYF7kaN+uizXEFJfhF2hlgwIv7BjWxt+k49jv8BAckdUc+brm8vrtZpbm1MnOOOq0Y9HLlVjNLc1Jw3W6sl7wUvb4tFCijnG+g2xmngjJ2cqCHc=,iv:QPxqQlCDu1B7Ki8KZGdLBj4P6AvJkDLHQ8J9HMsOCu0=,tag:NMmxWsgReNE5T+pSPTEyew==,type:str]
    BACKYARD_PATHWAY_CAMERA_1: ENC[AES256_GCM,data:fDfZsmtYOy9l4//cowkX40fFkwyh5uwRbOBe0MWM9MrzK2wpuzL4XrCEL4b0Zpyn5YHgrNUVzaYboWM9o6rreEd7pXwn10Qew3WXtcfQ0mxQQKAFZpwtvcIHvQ==,iv:qOwyEXucm6r31u9vkjwuKZvxd234hT1MiT4GgW4oOSs=,tag:+Lq6+D7IrsUoTD1vYb54EA==,type:str]
    SIDE_ALLEY_CAMERA_1: ENC[AES256_GCM,data:YqicNu5k+LLZDYbbIPvmSx7kif6i66W9WN0C3PpvJ9O7YEEt379p+sqKxOS9LrijRWlxSb4k1IVQv4UUZ3ZNrtpqtbxlZf4TK5fZBhX1E2b59ZbKI7w40+D6SA==,iv:c9ZazLU64vgGKKi8Ld2V8WS+b8iqhXlNn/a/MFClb78=,tag:0HCUhlKDBVsEMV2xt5wP0Q==,type:str]
    SIDE_ALLEY_CAMERA_2: ENC[AES256_GCM,data:lMp9i0dGKiMuSn/OJ9wLBtf33HQZFMZWCTKCX+79l5DzbaKMGiyONenExEgadSzFjtOCIV6/YvaziJooiFUiDLaq19zmEBirwGO2Jty2xugUNbGMgaP64n1ybw==,iv:fRW4ibHDC/scxcKjaoy1XX5z6BclWnIpXMaef+b2vIo=,tag:QUMtjIZYoRN93xQgv2wQ0A==,type:str]
    BACKYARD_CAMERA_2: ENC[AES256_GCM,data:oedLOHjyujBuRtbzx0X+1Nk0/5QfK506ddoBzBEpWv0LHVfKpkVUYSO2O4pf0CNhC9tRNFvXWEZf0lMpXrjzV+5XFSK/azwhvHII16mO0JGxGZeFS9sAPE7XiA==,iv:fmSGaKNMBzlVcqX//bRpXYFv0WqHFulwPACR99bsHS8=,tag:5U7cHdgr0YpkHTgeIv3nrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzj03r3dv3xrvtns0v0ufs4pvchw3u0564u36hc5h3vmxqu3gkq3wmu9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPekJWU09zZ1BvWGRIaGpD
            NWFya0lhUmMrd3cxN2Y2TFFLNFJOQWc3azF3Ck9oQzFXOG5oUFdiSTA2NStXTE1v
            K1ZDK3FaZzRWS0dOMGRtVldzaUpyQlEKLS0tIFJ3TllnQ3NEZFc3NmRZWG1VcHho
            aGpWMFVmeU5maUhQdzQ3R1ZVZXlpZFkK2MfXaYRbZ2ySCgDtuT/T+CqW6iBhVqBv
            AGuOYeJWa10YyJza5LJlr4XgDEB06YMk/AUzOZgEFwchFTP869Z38A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-30T17:18:54Z"
    mac: ENC[AES256_GCM,data:QxnNumlL5MyKvC+4w4U/xPxIVIg3dPzHD9BMy4HcajV8H25Jn/znlQtW3RfeZ99rNX89j2PJe+/jWRSD59IddF/fy6eQMb/ynqwdQG8er/+9e2EMUq3fpIDoCfeiyQYH14rzp2aIsb2JQB40beWfMX495A9LVYEIEI9L0/DfwM8=,iv:6ryWe5uwvGq1w9XjqdEEcbpbCu7YYLI6XSwV+Q/GsUs=,tag:bzaERRD8VLJuja4fMAuglg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
