---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  releaseName: node-red
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 2.0.5
    env:
      TZ: America/Phoenix
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    persistence:
      data:
        enabled: "true"
        existingClaim: node-red-config
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "internal"
        hosts:
          - host: automation.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "automation.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi