---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: comms
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts
      chart: matrix-synapse
      version: 2.1.36
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: matrixdotorg/synapse
      tag: v1.58.1
    serverName: ${SECRET_DOMAIN}
    publicServerName: matrix.${SECRET_DOMAIN}
    wellknown:
      enabled: false

    workers:
      media_repository:
        enabled: false

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: external
      className: external
      tls:
        - hosts:
            - matrix.${SECRET_DOMAIN}

    postgresql:
      enabled: true
      postgresqlPassword: ${MATRIX_POSTGRESQL_PASSWORD}
      image:
        repository: postgres
        tag: 14.3
      postgresqlDataDir: /var/lib/postgresql/data

    redis:
      enabled: true
      password: ${MATRIX_REDIS_PASSWORD}

    signingkey:
      job:
        enabled: false

    persistence:
      enabled: false