---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: comms
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts
      chart: matrix-synapse
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: matrixdotorg/synapse
      tag: v1.68.0
    serverName: ${SECRET_DOMAIN}
    publicServerName: matrix.${SECRET_DOMAIN}
    wellknown:
      enabled: true
      image:
        repository: sebp/lighttpd

    workers:
      media_repository:
        enabled: false

    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 10m
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_intercept_errors off;
      className: nginx
      tls:
        - hosts:
            - ${SECRET_DOMAIN}
            - matrix.${SECRET_DOMAIN}

    postgresql:
      enabled: true
      postgresqlPassword: ${SECRET_MATRIX_POSTGRES_PASSWORD}
      image:
        debug: true
      volumePermissions:
        enabled: true
      master:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                        - amd64

    redis:
      enabled: true
      password: ${SECRET_MATRIX_REDIS_PASSWORD}
      auth:
        password: ${SECRET_MATRIX_REDIS_PASSWORD}
      master:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                        - amd64

    signingkey:
      job:
        enabled: true

    persistence:
      enabled: false
