---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-books
  resources:
    requests:
      storage: 1Mi