---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app readarr
  namespace: media
spec:
  releaseName: *app
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: readarr
      version: 6.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.1.1352
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "books.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    env:
      TZ: "${TIMEZONE}"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config
      media:
        enabled: true
        type: nfs
        server: 192.168.1.50
        path: "/mnt/user/media/books"
      downloads:
        enabled: true
        type: nfs
        server: 192.168.1.50
        path: "/mnt/user/downloads"
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
