---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  releaseName: readarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: readarr
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.0.1083
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "internal"
        hosts:
        - host: "books.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "books.${SECRET_DOMAIN}"
    env:
      TZ: "America/Phoenix"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config
      media:
        enabled: true
        existingClaim: nfs-media-books-pvc
      downloads:
        enabled: true
        type: custom
        mountPath: "/downloads"
        readOnly: false
        volumeSpec:
          nfs:
            server: 192.168.1.50
            path: "/mnt/user/downloads"
    resources:
      requests:
        memory: 350Mi
        cpu: 50m
      limits:
        memory: 500Mi
