---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: flux
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.5.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/lokiraze/k3s-gitops/master/clusters/flux/flux/flux-values.yaml