---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - home
          - media
          - networking
      name: "you"
      customApps:
        - name: Some External Cluster Service
          url: http://192.168.1.100:5000
          icon: test-tube
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Reading
          links:
            - name: Instapaper
              url: "https://www.instapaper.com/u"
            - name: Medium
              url: "http://medium.com"
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: "${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${SECRET_DOMAIN}"
            secretName: "hajimari-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
