---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
    hajimari:
      defaultEnable: false
      title: "Lokiraze"
      namespaceSelector:
        matchNames:
          - default
          - home
          - media
          - networking
      name: "you"
      customApps:
        - name: Some External Cluster Service
          url: http://192.168.1.100:5000
          icon: test-tube
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Reddit
          links:
            - name: "/r/sysadmin"
              url: "https://www.reddit.com/r/sysadmin/"
            - name: "/r/selfhosted"
              url: "https://www.reddit.com/r/selfhosted/"
            - name: "/r/jellyfin"
              url: "https://reddit.com/r/jellyfin"
            - name: "/r/blackpeopletwitter"
              url: "https://reddit.com/r/blackpeopletwitter"
            - name: "/r/programming"
              url: "https://reddit.com/r/programming"
            - name: "/r/hacking"
              url: "https://reddit.com/r/hacking"
            - name: "/r/oscp"
              url: "https://reddit.com/r/oscp"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"
        - name: Self Hosted
          links:
            - name: Awesome SH
              url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
            - name: K8S@Home Charts
              url: "https://github.com/k8s-at-home/charts/tree/master/charts"
            - name: K8S@Home Search
              url: https://whazor.github.io/k8s-at-home-search/
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: http://authelia.security.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Method $request_method;
        hosts:
          - host: "${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
